## artifactid.nim — RFC-0006 M-artifact-identity: PURE identity + ratio core
## (pass (a) of the slice — see the RFC's M-artifact-identity bullet and its
## `normalize()` sub-bullet, plus the handoff's "2 sequenced passes" note).
##
## This module is the pure identity + ratio core (pass (a)); the runner.nim
## hook, artifact-ledger emission, and measurement-mode gate it once lacked
## are now built in pass (b) (`measureworker.nim` + `runner.nim`'s
## measurement-worker wiring — see those modules). Every effectful step here
## is still an injectable seam, mirroring `ccprobe.RunProc` (cmd,args)->
## (output,ok) and `compiledriver.CompileDriver`'s closure-field idiom —
## never a bare unseamed I/O call.
##
## ## normalize() — EXACT known-string erasure, not regex/heuristic
##
## crisol *constructs* the per-slot `cacheDir`/`binDir` strings itself
## (`runner.nim`: `cachePath(ep, config) & "_" & $pepIdx` /
## `binPath(ep, config) & "_" & $pepIdx`), so normalization is a literal
## substring-erase of those KNOWN strings — never a regex that guesses which
## paths "look like" slot paths (that risks over-stripping a real project
## `-I`). `normalize()` runs the same three steps on BOTH the `.c` file's
## content and the `ccCmd` string (the caller passes whichever it has; each
## step is a no-op where it does not apply to that content's shape):
##
##   1. Strip the fixed 4-line Nim-generated header comment block — but ONLY
##      when the content actually starts with Nim's own generated-header
##      marker (`/* Generated by Nim Compiler`). A vendor `{.compile.}` `.c`
##      file (e.g. this slice's golden fixture's `fixture.c`) is NOT
##      Nim-generated and carries no such marker, so this step is a genuine
##      no-op for it — unlike a blind "chop the first 4 lines" scaffold,
##      which would corrupt a vendor file's own leading comment. A `ccCmd`
##      string never starts with the marker either, so this step is also a
##      no-op there.
##   2. Inline-hash `@response-file` arguments: cc's OWN response-file
##      syntax is an argv token beginning with a literal `@` (GCC: "@file
##      reads command-line options from file"). Detecting that token is
##      exact (checking the first byte of a whitespace-delimited token), not
##      a heuristic guess about path shapes. The referenced file's CONTENT
##      is read via the injectable `readFile` seam and folded into a short
##      digest that replaces the token in place — so a `.rsp`-only content
##      change becomes visible in the normalized string even though the
##      literal `@path` token itself does not change. Every other byte
##      (including all whitespace/newlines) is preserved untouched, so this
##      never reformats a `.c` file's body.
##   3. Erase every known `cacheDir`/`binDir` string, verbatim, in the order
##      given. These are the exact strings the CALLER constructed (never
##      re-derived or guessed here).
##
## ## ccIncludeClosure() — the FULL `cc -M` #include closure
##
## Per RFC-0006's soundness argument, `.c`-content identity alone is only an
## UPPER BOUND on safely-reusable identity: the cc also reads the module's
## full transitive `#include` closure, and a distro header backport that
## patches a struct layout without moving a version string must invalidate
## the key. `ccIncludeClosure` derives a `cc -M` (not `-MM` — system headers
## included, per the RFC's soundness argument that a libc/header upgrade
## must be visible too) invocation from the manifest's own `ccCmd`.
##
## **Review Finding 1 (soundness): REPLICATE, never allow-list.** An earlier
## version of `deriveCcMInvocation` kept only tokens starting with
## `-I`/`-D`/`-std` and dropped everything else. GCC/Clang have OTHER flags
## that change header resolution — `-isystem`, `-iquote`, `-idirafter`,
## `-include`, `-imacros`, `-iprefix`, `-nostdinc`, and more — reachable via
## a project's `--passC`. Dropping one of these means the probe searches
## DIFFERENT directories than the real compile: a header reachable ONLY via
## a dropped flag can change in place (same path text, same `.c`, same
## normalized cc command) without changing `includeClosureContentHash` —
## identical key/preimage, wrong-hit. `deriveCcMInvocation` therefore
## REPLICATES the real `ccCmd`'s arguments verbatim and only REMOVES what
## must not be there for a `-M` dependency-listing run: the compile-action
## flag `-c`, and the output flag `-o <obj>` (both the space-separated and
## fused `-o<obj>` forms). Every other flag — `-I`/`-D`/`-std`/`-isystem`/
## `-iquote`/`-include`/`-nostdinc`/anything else — survives untouched, so
## the probe resolves headers under EXACTLY the same search path the real
## compile used. Then runs the result through the injectable `RunProc` seam
## (`crisol/ccprobe`'s own (cmd,args)->(output,ok) shape — reused, not
## reinvented) and parses the Make-style dependency output into the header
## set. Each header's CONTENT (not just its path) is hashed via the
## injectable `FileReaderProc` seam, folded exactly like `depgraph.
## closureContentHash` (sorted paths, chained FNV-1a, path+content both
## mixed in) — mirrored, not reinvented.
##
## ## artifactKeyHash() — the Stage-R key material hash
##
## `normalized(ccCmd) ⊕ normalized .c content ⊕ full cc -M #include-closure
## content-hash`, using `keys.soundnessKey`'s own per-component-wrapped
## chained-FNV-1a idiom (`keys.chainComponent` is module-private to
## `keys.nim`; the 4-line helper is duplicated here rather than exported
## across an unrelated import — the same deliberate, documented choice
## `artifactledger.nim` makes for its `bootId` duplication).
##
## The RFC states Stage M must measure "on the exact key material Stage R
## would use" — `stageRKey` (objkey.nim) additionally folds `nimVersion`/
## `ccVersion` (toolchain fingerprint, constant within one run — irrelevant
## to cross-entrypoint sharing WITHIN that run) and `normalize(ccCmd)` (a
## REAL per-unit flag delta that two entrypoints can genuinely differ on).
## Omitting `ccCmd` here let M over-count sharing: two units with identical
## `.c` + closure but a real cc-flag delta would count as SHARED under M's
## ratio while genuinely MISSING under R's key. Folding `normalizedCcCmd`
## makes M's key a true PREFIX of R's (differing only by the
## legitimately-constant-within-a-run nimVersion/ccVersion suffix) — see
## `docs/rfc/0006-cross-entrypoint-compile-reuse.md` §Soundness and the
## stage-4 review's R5 finding.
##
## `normalizedCcCmd` is the LAST parameter with a `""` default — not the
## first, despite being folded FIRST internally — so existing 2-arg call
## sites (the committed golden-fixture oracle test, which pins closed-form
## r_size/r_time numbers over a FIXED, uniform per-run cc command and so is
## insensitive to which constant gets folded in, as long as it's the SAME
## constant for every call in that file) keep compiling and computing
## unchanged. The production caller (`measureworker.recordArtifactRows`)
## passes the real normalized cc command explicitly.
##
## ## reuseRatios() — r_time (PRIMARY) and r_size (secondary)
##
## Pure, over `ArtifactRecord`s mirroring `artifactledger.ArtifactRow`'s
## field shape. A unit is "shared" iff its `keyHash` is carried by ≥2
## DISTINCT entrypoints within its (`groupId`,`configHash`) segment.
## `r_time = sharedCcTime / totalCcTime` (cc-time-weighted, the decision
## gate's PRIMARY metric — RFC-0006 Motivation's "wrong weighting answers
## the wrong question" trap); `r_size` is the size-weighted secondary,
## storage-planning analog. Segmented by group/config, mirroring M-report's
## segmentation.

import std/[algorithm, sets, strutils, tables]
import crisol/depgraph   # re-uses fnv1a64, toHex16, fnvOffset64; never reimplement
import crisol/ccprobe    # re-uses the RunProc (cmd,args)->(output,ok) seam idiom
export ccprobe.RunProc
export ccprobe.realRun

# ---------------------------------------------------------------------------
# Seam: file reader (response-file inlining + header-closure content hashing)
# ---------------------------------------------------------------------------

type
  FileReaderProc* = proc(path: string): tuple[content: string; ok: bool] {.closure.}
    ## Never raises; failure (missing/unreadable file) surfaces as ok=false.

proc realFileReader*(path: string): tuple[content: string; ok: bool] =
  ## Default seam: std/os `readFile`. Never raises.
  try:
    result = (content: readFile(path), ok: true)
  except CatchableError:
    result = (content: "", ok: false)

# ---------------------------------------------------------------------------
# Internal: chainComponent — mirrors keys.chainComponent exactly (see module
# doc for why this small helper is duplicated rather than imported).
# ---------------------------------------------------------------------------

proc chainComponent(running: uint64; component: string): uint64 {.inline.} =
  let compDigest = toHex16(fnv1a64(component))
  fnv1a64(toHex16(running) & "\x00" & compDigest)

# ---------------------------------------------------------------------------
# normalize()
# ---------------------------------------------------------------------------

const NimGeneratedHeaderMarker* = "/* Generated by Nim Compiler"
  ## The fixed marker that opens every Nim-generated `.c` file's leading
  ## 4-line comment block (verified against real 2.2.10 output — see
  ## `tests/fixtures/golden_reuse`). Exported so tests/callers can assert
  ## against the same literal without re-guessing it.

proc stripNimGeneratedHeader(content: string): string =
  ## Drop the fixed 4-line Nim-generated comment header IF `content` starts
  ## with `NimGeneratedHeaderMarker`; otherwise return `content` unchanged
  ## (a vendor `.c` file or a `ccCmd` string never carries this marker).
  ## Bounded: exactly 4 newlines from the start — not a parser.
  if not content.startsWith(NimGeneratedHeaderMarker):
    return content
  var idx = 0
  var newlines = 0
  while idx < content.len and newlines < 4:
    if content[idx] == '\n': inc newlines
    inc idx
  result = if idx >= content.len: content else: content[idx .. ^1]

proc inlineResponseFiles(s: string; readFile: FileReaderProc): string =
  ## Replace every whitespace-delimited `@path` token with `@<contentHash>`,
  ## reading `path`'s real content through the injected seam. Every other
  ## byte (including all whitespace/newlines) is copied through unchanged —
  ## this is a surgical in-place scan, never a retokenize-and-rejoin, so it
  ## cannot reformat a multi-line `.c` file's body.
  result = newStringOfCap(s.len)
  var i = 0
  while i < s.len:
    let atTokenStart = i == 0 or s[i - 1] in {' ', '\t', '\n', '\r'}
    if s[i] == '@' and atTokenStart:
      var j = i + 1
      while j < s.len and s[j] notin {' ', '\t', '\n', '\r'}:
        inc j
      let path = s[i + 1 ..< j]
      if path.len > 0:
        let (content, ok) = readFile(path)
        let digestSrc = if ok: content else: "<unreadable:" & path & ">"
        result.add "@"
        result.add toHex16(fnv1a64(digestSrc))
      else:
        result.add s[i]
      i = j
    else:
      result.add s[i]
      inc i

proc eraseKnownString(s, known: string): string =
  ## Erase every occurrence of `known` in `s`, EXCEPT where the match is
  ## immediately followed by an identifier character (letter/digit/`_`) —
  ## a superstring-boundary guard (R14-T7 finding). A blind `s.replace(known,
  ## "")` corrupts a real project token that happens to have `known` as a
  ## PREFIX (e.g. known cacheDir `/proj/gen/ep_a_3`, real flag
  ## `-I/proj/gen/ep_a_3_vendor` — a naive replace would strip the shared
  ## prefix and leave a mangled `-I_vendor`). This stays EXACT-string
  ## matching (never a path-shape regex, per the module doc's discipline) —
  ## only a boundary check is added, and on the ambiguous case it declines to
  ## erase (leaving the known string present) rather than risk corrupting a
  ## different token: a false negative here only under-counts reuse, never
  ## falsely claims it.
  ##
  ## CAVEAT: only the TRAILING boundary is guarded (the char immediately
  ## after the match). This is sound today only because every production
  ## `knownStrings` value is an absolute (`/`-anchored) path (see callers:
  ## `nimcacheDir`/`outputBinPath.parentDir()`) — `/` is never an
  ## `IdentChars` char, so a leading identifier prefix can never fuse with
  ## an absolute-path match into one token. A future caller passing a
  ## non-`/`-anchored known string (e.g. a bare basename) could hit a
  ## leading-boundary false-erase (stripping it out of a larger identifier
  ## it's merely a suffix of). Guard both boundaries if this is ever reused
  ## outside the current absolute-path call sites.
  if known.len == 0: return s
  result = newStringOfCap(s.len)
  var i = 0
  while i < s.len:
    if i + known.len <= s.len and s[i ..< i + known.len] == known:
      let nextIdx = i + known.len
      let boundaryOk = nextIdx >= s.len or s[nextIdx] notin IdentChars
      if boundaryOk:
        i = nextIdx
        continue
    result.add s[i]
    inc i

proc normalize*(content: string; knownStrings: openArray[string];
                readFile: FileReaderProc = realFileReader): string =
  ## EXACT known-string erasure (see module doc). `knownStrings` are the
  ## exact `cacheDir`/`binDir` strings the CALLER constructed — never
  ## guessed here. Erasure is boundary-guarded against superstring
  ## corruption (see `eraseKnownString`, R14-T7).
  result = stripNimGeneratedHeader(content)
  result = inlineResponseFiles(result, readFile)
  for known in knownStrings:
    if known.len > 0:
      result = eraseKnownString(result, known)

# ---------------------------------------------------------------------------
# ccIncludeClosure()
# ---------------------------------------------------------------------------

proc shellSplit*(s: string): tuple[toks: seq[string]; ok: bool] =
  ## **Exported (review Finding 2).** Originally module-private, but two
  ## other call sites tokenize this SAME manifest `ccCmd` shape and MUST
  ## tokenize identically to `deriveCcMInvocation`'s own use below, or a
  ## whitespace-containing path (realistic under WSL2 — the RFC itself calls
  ## this out) silently corrupts their derivation instead of failing loudly:
  ## `compiledriver.parseCcOutputObj` (extracting `-o <obj>`) and
  ## `cacheworker.buildCacheKeyOf` (deriving the `.c` source path). Before
  ## this export both used a plain `splitWhitespace()`, which — unlike this
  ## tokenizer — has no concept of quoting at all, so it silently mis-splits
  ## a shell-quoted space-containing argument instead of degrading via `ok`.
  ##
  ## Minimal POSIX-shell-like tokenizer: single-quoted segments (literal, no
  ## escapes inside — matches `sh`), double-quoted segments (backslash
  ## escapes `\\`, `\"`, `\$`, `` \` `` inside — matches `sh`), and
  ## backslash-escaping outside quotes. Whitespace (space/tab/newline/CR)
  ## separates tokens outside quotes. `ok = false` on an unterminated quote
  ## or a trailing unescaped backslash — cases this parser cannot
  ## disambiguate; callers MUST treat that as a derivation failure
  ## (fail-safe: never guess, never emit a wrong-but-plausible tokenization).
  ##
  ## This is deliberately the SAME quoting convention `std/os.quoteShellPosix`
  ## produces (single-quote-wrap, `'\''`-escape for an embedded quote), so it
  ## correctly round-trips a Nim-generated cc command whose `-I` argument
  ## contains a space (realistic under WSL2 / a mounted toolchain) — the real
  ## compile runs that same string through a shell (`execProcesses`'s
  ## `poEvalCommand` — see compiledriver.nim's module doc), so deriving the
  ## `cc -M` probe args must tokenize identically or the probe silently runs
  ## with wrong/omitted flags (R1b).
  var toks: seq[string]
  var cur = ""
  var haveCur = false
  var i = 0
  let n = s.len
  while i < n:
    let c = s[i]
    case c
    of ' ', '\t', '\n', '\r':
      if haveCur:
        toks.add cur
        cur = ""
        haveCur = false
      inc i
    of '\'':
      haveCur = true
      inc i
      while i < n and s[i] != '\'':
        cur.add s[i]
        inc i
      if i >= n:
        return (toks: newSeq[string](), ok: false)   # unterminated single quote
      inc i   # skip closing quote
    of '"':
      haveCur = true
      inc i
      while i < n and s[i] != '"':
        if s[i] == '\\' and i + 1 < n and s[i + 1] in {'\\', '"', '$', '`'}:
          cur.add s[i + 1]
          i += 2
        else:
          cur.add s[i]
          inc i
      if i >= n:
        return (toks: newSeq[string](), ok: false)   # unterminated double quote
      inc i   # skip closing quote
    of '\\':
      haveCur = true
      if i + 1 < n:
        cur.add s[i + 1]
        i += 2
      else:
        return (toks: newSeq[string](), ok: false)   # trailing unescaped backslash
    else:
      haveCur = true
      cur.add c
      inc i
  if haveCur:
    toks.add cur
  result = (toks: toks, ok: true)

proc deriveCcMInvocation*(ccCmd: string):
    tuple[cmd: string; args: seq[string]; sourceFile: string; ok: bool] =
  ## Derive a `cc -M` dependency-generation invocation from one manifest
  ## `ccCmd` string (see `closure.parseCompileManifest`).
  ##
  ## **Review Finding 1 (soundness): REPLICATE the real command, don't
  ## allow-list.** Every flag token survives VERBATIM except the two that
  ## must not be there for a `-M` run: the compile-action flag `-c`, and the
  ## output flag `-o <obj>` — removed in EITHER its space-separated form
  ## (the `-o` token AND the single token immediately following it) or its
  ## fused form (a token starting with `-o` and longer than 2 characters,
  ## e.g. `-ofoo`; that token alone is dropped, it has no separate argument).
  ## `-M` is prepended and the original source file (the command's last
  ## shell token — matching `closure.parseCompileManifest`'s own convention
  ## that the compiled `.c` is always the final argument) is appended last.
  ## See the module doc's "ccIncludeClosure()" section for WHY this must be
  ## a denylist of exactly these two things, never an allow-list of flags
  ## assumed to matter: any OTHER flag (`-isystem`, `-iquote`, `-include`,
  ## `-nostdinc`, …) changes header resolution just as much as `-I`/`-D`/
  ## `-std` and must reach the probe unchanged.
  ##
  ## Tokenizes via `shellSplit` — shell-AWARE (R1b), not a naive
  ## `splitWhitespace` — because the real compile runs `ccCmd` through a
  ## shell (compiledriver's `execProcesses`/`poEvalCommand`), so a
  ## whitespace-naive split would mis-tokenize a shell-quoted path
  ## containing a space and silently derive a WRONG-but-nonempty probe
  ## (feeds R1's soundness bug). `ok = false` (R4/R1b) — never a raise, never
  ## a `Defect` — whenever the command can't be cleanly tokenized (an
  ## unterminated quote) OR has fewer than 2 tokens (no source file to
  ## target): a per-unit oddity must degrade, never crash the worker past
  ## its `except CatchableError` escape hatch (R4).
  let (toks, splitOk) = shellSplit(ccCmd)
  if not splitOk or toks.len < 2:
    return (cmd: "", args: newSeq[string](), sourceFile: "", ok: false)
  let cc = toks[0]
  let sourceFile = toks[^1]
  var kept: seq[string] = @["-M"]
  var idx = 1
  while idx < toks.len - 1:
    let t = toks[idx]
    if t == "-c":
      inc idx   # drop the compile-action flag
      continue
    if t == "-o":
      idx += 2   # drop the flag AND its separated argument
      continue
    if t.startsWith("-o") and t.len > 2:
      inc idx   # drop the fused "-o<obj>" form (no separate argument)
      continue
    kept.add t
    inc idx
  kept.add sourceFile
  result = (cmd: cc, args: kept, sourceFile: sourceFile, ok: true)

proc parseCcMDeps*(ccMOutput: string): seq[string] =
  ## Parse GNU-make-style dependency output (`target: dep1 dep2 \` with
  ## backslash line continuations) into the flat list of dependency tokens,
  ## INCLUDING the source file itself (callers that need it excluded should
  ## filter by the known source path — see `ccIncludeHeaders`).
  let joined = ccMOutput.replace("\\\r\n", " ").replace("\\\n", " ")
  let colonIdx = joined.find(':')
  let depsStr = if colonIdx >= 0: joined[colonIdx + 1 .. ^1] else: joined
  for tok in depsStr.splitWhitespace():
    result.add tok

proc ccIncludeHeaders*(ccMOutput: string; sourceFile: string): seq[string] =
  ## The header set: every dependency `cc -M` reports EXCEPT the compiled
  ## source file itself (excluded by exact match on the known path used to
  ## derive the invocation — never guessed).
  for p in parseCcMDeps(ccMOutput):
    if p.len > 0 and p != sourceFile:
      result.add p

proc includeClosureContentHash*(headerPaths: seq[string];
                                readFile: FileReaderProc = realFileReader): string =
  ## Content-hash the full header set, mirroring `depgraph.
  ## closureContentHash`'s exact fold (sorted paths; chained FNV-1a mixing
  ## BOTH path and content per step — order-independent for the same set,
  ## but path- and content-sensitive). Uses the injectable `readFile` seam
  ## (never raises) rather than `depgraph`'s raising `readFile` call, since
  ## a header from `/usr/include` may legitimately be probed without a hard
  ## failure path in a pure-core unit test.
  var sorted = headerPaths
  sorted.sort()
  var running: uint64 = fnvOffset64
  for p in sorted:
    let (content, ok) = readFile(p)
    let c = if ok: content else: "<unreadable:" & p & ">"
    running = fnv1a64(toHex16(running) & "\x00" & p & "\x00" & c)
  result = toHex16(running)

proc ccIncludeClosure*(ccCmd: string; run: RunProc = realRun;
                       readFile: FileReaderProc = realFileReader):
    tuple[headers: seq[string]; contentHash: string; ok: bool] =
  ## Derive + run the `cc -M` invocation (via the injectable `RunProc` seam
  ## — `crisol/ccprobe`'s own seam type, reused not reinvented) and fold the
  ## resulting header set's CONTENT into a single hash. `ok = false` (with
  ## empty headers/hash) iff EITHER the invocation could not be cleanly
  ## derived (R1b/R4 — `deriveCcMInvocation` degrade: too few tokens or an
  ## unterminated shell quote) OR the `cc -M` invocation itself failed; never
  ## raises.
  let inv = deriveCcMInvocation(ccCmd)
  if not inv.ok:
    return (headers: newSeq[string](), contentHash: "", ok: false)
  let (output, ranOk) = run(inv.cmd, inv.args)
  if not ranOk:
    return (headers: newSeq[string](), contentHash: "", ok: false)
  let headers = ccIncludeHeaders(output, inv.sourceFile)
  result = (headers: headers,
            contentHash: includeClosureContentHash(headers, readFile),
            ok: true)

# ---------------------------------------------------------------------------
# artifactKeyHash()
# ---------------------------------------------------------------------------

proc artifactKeyHash*(normalizedC: string; includeClosureContentHash: string;
                      normalizedCcCmd: string = ""): string =
  ## The Stage-M key material hash: `normalized(ccCmd) ⊕ normalized .c
  ## content ⊕ full cc -M #include-closure content-hash` (R5 fix — see
  ## module doc §artifactKeyHash(): a true PREFIX of Stage R's `stageRKey`,
  ## which additionally folds nimVersion/ccVersion). `normalizedCcCmd`
  ## defaults to "" for backward compatibility with existing 2-arg call
  ## sites (module doc explains why this is safe).
  var running: uint64 = fnvOffset64
  running = chainComponent(running, normalizedCcCmd)
  running = chainComponent(running, normalizedC)
  running = chainComponent(running, includeClosureContentHash)
  result = toHex16(running)

# ---------------------------------------------------------------------------
# reuseRatios()
# ---------------------------------------------------------------------------

type
  ArtifactRecord* = object
    ## One per-entrypoint reusable-unit observation — mirrors
    ## `artifactledger.ArtifactRow`'s field shape (this module does not
    ## import/depend on that module; the shape is mirrored deliberately so
    ## a future pass (b) writer can construct one directly from the other).
    entrypointIdentity*: string  ## distinguishes WHICH entrypoint carries this unit
    groupId*:            string  ## segmentation
    configHash*:         string  ## segmentation
    basename*:           string  ## generated .c basename
    keyHash*:            string  ## artifactKeyHash() output (or any opaque key)
    sizeBytes*:          int64
    ccTimeUs*:           int64

  ReuseSegmentKey* = tuple[groupId, configHash: string]

  ReuseRatios* = object
    rTime*:          float   ## PRIMARY: cc-time-weighted reuse ratio
    rSize*:          float   ## secondary: size-weighted reuse ratio
    totalCcTimeUs*:  int64
    sharedCcTimeUs*: int64
    totalBytes*:     int64
    sharedBytes*:    int64

proc reuseRatios*(records: seq[ArtifactRecord]): Table[ReuseSegmentKey, ReuseRatios] =
  ## Compute `r_time` (PRIMARY) and `r_size` (secondary) per (`groupId`,
  ## `configHash`) segment. A record is "shared" iff its `keyHash` is
  ## carried by ≥2 DISTINCT `entrypointIdentity` values within its own
  ## segment (deduplicated — the same entrypoint appearing twice for the
  ## same keyHash does not itself constitute sharing).
  var bySegment: Table[ReuseSegmentKey, seq[ArtifactRecord]]
  for r in records:
    let segKey: ReuseSegmentKey = (groupId: r.groupId, configHash: r.configHash)
    bySegment.mgetOrPut(segKey, newSeq[ArtifactRecord]()).add r

  for segKey, segRecords in bySegment:
    var entrypointsByKey: Table[string, HashSet[string]]
    for r in segRecords:
      entrypointsByKey.mgetOrPut(r.keyHash, initHashSet[string]()).incl r.entrypointIdentity

    var totalCc, sharedCc, totalBytes, sharedBytes: int64
    for r in segRecords:
      totalCc += r.ccTimeUs
      totalBytes += r.sizeBytes
      if entrypointsByKey[r.keyHash].len >= 2:
        sharedCc += r.ccTimeUs
        sharedBytes += r.sizeBytes

    let rTime = if totalCc == 0: 0.0 else: sharedCc.float / totalCc.float
    let rSize = if totalBytes == 0: 0.0 else: sharedBytes.float / totalBytes.float
    result[segKey] = ReuseRatios(rTime: rTime, rSize: rSize,
                                 totalCcTimeUs: totalCc, sharedCcTimeUs: sharedCc,
                                 totalBytes: totalBytes, sharedBytes: sharedBytes)
