## crisol.nim — CLI entry point (A5 + B6 + B7 + C2 + C3)
##
## Thin shell: parse argv → apply overrides → wire pipeline → exit.
## No business logic lives here; all orchestration is in the library.
##
## Usage:
##   crisol run [<path>...]
##     --group <name>    run named group(s) instead of defaults (repeatable)
##     --all-groups      include opt-in groups (gates still apply)
##     --jobs <N>        parallel job cap (default: max(1, cpu-2))
##     --timeout <secs>  per-entrypoint run-timeout override
##     --fail-fast       stop launching new entrypoints on first failure
##     --dry-run         compute & print the plan; do NOT compile or run
##     --json            machine-readable output
##     --failed          re-run only entrypoints that failed in the last run
##     --filter-tag TAG  reporting-level filter: show only records tagged TAG;
##                       emits a warning to stderr when no records match
##   crisol list [<path>...] [--group <name>] [--all-groups]
##     --json            machine-readable plan output
##   crisol clean [--all]
##     --all             remove entire .crisol/ state dir (no lock needed)
##
## --group and --all-groups are mutually exclusive: specifying both is a usage
## error (exit 3).  Precedence: error is cleaner than silent last-wins because
## the two flags are semantically contradictory (named subset vs. full set).
##
## `list` and `run --dry-run` are the SAME pure plan phase (discover →
## applyGates → plan) with execution skipped — they share pipeline.buildRunPlan
## and emitPlan (CLI); neither spawns a subprocess.
##
## Exit codes (per RFC §CLI Surface):
##   0   all entrypoints passed (or a pure listing succeeded)
##   1   one or more entrypoints failed / compile-failed / timed-out / signaled
##   2   crisol internal error (should never occur in normal operation)
##   3   environment/configuration error: bad args, zero entrypoints discovered,
##       --failed with no prior run (lastrun.json absent)

import std/[options, os, strutils]
import std/terminal as stdterm  # isatty(File) — cross-platform TTY check, no
                                # std/posix needed (RFC-0007 A3); distinct
                                # from crisol/terminal (color rendering) below
import crisol/[clean, terminal, api, config, lock, junit, shard, order, workerplan, measureworker, ccprobe, nimprobe, render, ioutils]
import crisol/process  # rfc-0007 A7: capabilities() -- the real substrate node for run/v2 + plan/v1

# `_exit(2)`: skips Nim's exitprocs/GC-finalize cleanup on the int8-overflow
# exit-code bypass below. A raw single-symbol libc import (not a
# `std/posix` module dependency) — same pattern runner.nim already uses for
# `mkdtemp` (RFC-0007 A2b), kept here rather than moved to `ioutils` because
# it is process-exit, not file I/O.
proc exitnow(code: cint) {.importc: "_exit", header: "<unistd.h>", noreturn.}

# ---------------------------------------------------------------------------
# Exit codes (RFC §CLI Surface)
# ---------------------------------------------------------------------------

const
  ExitOk*          = 0
  ExitTestFailure* = 1
  ExitInternal*    = 2
  ExitEnvironment* = 3

# ---------------------------------------------------------------------------
# Version — parsed from crisol.nimble at compile time via staticRead.
# Works under both `nimble build` AND `nim r --path:src` (the project's own
# test bootstrap).  gorge/NimblePkgVersion are NOT used: gorge shells out at
# compile time and is fragile in sandboxed containers; NimblePkgVersion is only
# injected by nimble tasks, not by plain nim r.
# ---------------------------------------------------------------------------

const CrisolNimble = staticRead("../crisol.nimble")

func parseNimbleVersion(src: string): string =
  ## Extract the `version = "x.y.z"` line's value from a .nimble file.
  ## Returns "" if the line is absent or malformed.
  for line in src.splitLines():
    let s = line.strip()
    if s.startsWith("version") and s.len > 7 and s[7] in {' ', '\t', '='}:
      let eq = s.find('=')
      if eq < 0: continue
      var v = s[eq+1..^1].strip()
      if v.len >= 2 and v[0] == '"' and v[^1] == '"':
        return v[1..^2]
  return ""

const CrisolVersion* = parseNimbleVersion(CrisolNimble)

static:
  doAssert CrisolVersion.len > 0 and CrisolVersion[0] in {'0'..'9'},
    "crisol: failed to parse version from crisol.nimble — check the version = line"

# ---------------------------------------------------------------------------
# Init template — canonical starter crisol.kdl (S6).
# MUST use only known config keys so loadConfig parses it with zero warnings.
# ---------------------------------------------------------------------------

const InitTemplate* = """// crisol.kdl — canonical starter configuration
// Generated by `crisol init`.  Edit to suit your project.
// Reference: https://github.com/coreyleavitt/crisol  (see docs/rfc/0003-*)

// ---------------------------------------------------------------------------
// Global settings (all optional — defaults shown)
// ---------------------------------------------------------------------------

// jobs 0                    // 0 = auto (max(1, cpu_count - 2))
// timeout-secs 300          // per-entrypoint run timeout
// compile-timeout-secs 600  // per-entrypoint compile timeout
// max-output-bytes 10485760  // stdout+stderr cap per entrypoint

// State directory (relative to this file).  Change only if .crisol/ conflicts.
// state-dir ".crisol"

// ---------------------------------------------------------------------------
// Groups — at least one required
// ---------------------------------------------------------------------------

group "unit" {
    // Globs are relative to the project root (the directory containing this file).
    globs "tests/unit/test_*.nim"
}

// Opt-in group example: only runs when --all-groups or --group integration is passed.
// Remove or uncomment and customise as needed.
//
// group "integration" {
//     globs "tests/integration/test_*.nim"
//     opt-in #true
// }

// Gate example: run this group only when CI=true is set in the environment.
// Gates are evaluated at runtime; a closed gate skips the group (not an error).
//
// group "slow" {
//     globs "tests/slow/test_*.nim"
//     opt-in #true
//     gate "CI"
// }
"""

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------

proc usage(): string =
  """crisol — host-side test runner

Usage:
  crisol run  [<path>...] [--group <name>]... [--all-groups]
              [--jobs <N>] [--timeout <secs>] [--fail-fast]
              [--dry-run] [--json] [--force-compile]
              [--failed] [--changed [--base <ref>]]
              [--filter-tag <tag>]
              [--retries <N>] [--fail-on-flaky] [--strict-hygiene]
              [--order <recent-fail|duration|none>]
              [--hermetic <none|isolated|network>]
              [--rlimit-nofile <N>]
              [--env-pin NAME=VALUE]...
              [--no-remote-cache]
              [--explain-miss | --explain-miss-verbose]
              [--cache-stats]
              [--verify-cache [--verify-cache-pct <N>]
                              [--verify-cache-seed <N>] [--verify-cache-strict]]
  crisol list [<path>...] [--group <name>]... [--all-groups] [--json]
  crisol closure <entrypoint>... [--json] [--config <path>]
  crisol closure --all [--json] [--config <path>]
  crisol clean [--all] [--config <path>]

  crisol --help | -h
  crisol --version | -V | version

Subcommands:
  run      Discover, compile, and run test entrypoints.
  list     Show what WOULD run (the plan) without compiling or running anything.
  closure  Read-only: show the recorded depgraph entry (group, flagHash,
           closure files, closureHash) for one or more planned entrypoints,
           or every discovered entrypoint with --all.  No compile, no run,
           no lock.
  clean    Prune orphan cache/bin dirs and stale depgraph entries.
           --all removes the entire state dir.  --config overrides the config file.

Options for 'run' and 'list':
  <path>...       Restrict discovery to these paths/globs (default: convention
                  globs from config — tests/unit/test_*.nim, etc.).
  --group <name>  Run only the named group(s); repeatable.  Mutually exclusive
                  with --all-groups (specifying both is a usage error).
  --all-groups    Include opt-in groups (gates still apply).

Additional options for 'run':
  --jobs N, -j N  Parallel job cap.  Default: max(1, cpu_count - 2).
  --timeout S, -t S
                  Per-entrypoint run timeout in seconds.  Default: 300.
  --fail-fast     Stop launching new entrypoints after the first failure.
  --dry-run       Print the plan (selection + per-entrypoint compile decisions)
                  and exit; compile and run NOTHING.
  --json          Emit machine-readable JSON to stdout instead of human output.
  --failed        Re-run only entrypoints that failed in the last run
                  (reads .crisol/lastrun.json; exit 3 if absent).
  --changed       Impact selection: run only entrypoints whose dependency
                  closure intersects the git diff.  Requires a git work tree
                  (exit 3 otherwise).  Combined with --failed, selects the
                  UNION of the two narrowed sets.
  --base <ref>    With --changed, diff the working tree against <ref> instead
                  of HEAD (includes uncommitted edits).  Ignored (with a
                  warning) when --changed is absent.
  --force-compile Force recompilation of all entrypoints even when fresh.
  --filter-tag T  Reporting-level filter: show ONLY test records tagged T.
                  Entrypoints still run in full; only the report is filtered.
                  Emits a warning to stderr when no records match the tag.
                  Exit code is unchanged by the filter.
  --order <mode>  History-based execution order: recent-fail (surface recently-
                  failing tests first for minimum time-to-first-failure),
                  duration (longest-running first for best parallelism),
                  or none (default: no reorder).
  --strict-hygiene
                  A would-be pass with an OBSERVED escapee (a leaked same-
                  process-group descendant still running at reap time) is
                  reported as a failure (exit 1) instead of a pass.  Off by
                  default: an escapee is still shown ([ESCAPEE] warning,
                  evidence.escapees on the wire) but does not fail the run.
                  Also settable via crisol.kdl's `strict-hygiene #true`.
  --hermetic <L>  Hermeticity level for child sandboxes: none (no env scrub /
                  no rlimits / inherit parent env), isolated (default: env
                  allowlist + isolated tmpdir + config-declared rlimits), or
                  network (superset of isolated + net-ns isolation; currently
                  degrades — net-ns not wired — so such runs are not cached).
  --rlimit-nofile N
                  Override RLIMIT_NOFILE (max open fds) for hermetic sandbox
                  children.  Default: 1024 (or crisol.kdl's `rlimit-nofile`,
                  if set).  Raise this for fd-heavy consumer workloads (e.g.
                  one eventfd per in-flight async call) without patching
                  crisol.
  --env-pin NAME=VALUE
                  Pin an env var into every child's environment, regardless
                  of the host's own value for NAME (repeatable). The pinned
                  value -- not the host's -- enters the soundness key, so a
                  pinned variable is cache-key-stable across hosts. Also
                  settable via crisol.kdl's `env-pin "NAME" "VALUE"` (CLI
                  wins on a name collision). Nothing is pinned by default.
  --measure-compile-reuse
                  Diagnostic: run compile slots through the measurement
                  worker and emit the `compile` block's segmented cc%/
                  r_time/r_size stats to the run report (no caching).
  --explain-miss  On a cache miss, name which of the 9 soundness-key
                  components changed since the last recorded attempt for
                  that entrypoint (and, for the env component, which
                  variable). Requires local history from a prior run on
                  this stateDir -- an entrypoint with no prior record
                  reports "no prior inputs recorded" instead. Also settable
                  via crisol.kdl's `explain-miss #true`. In --json mode
                  this renders to stderr (stdout stays parseable JSON) and
                  the run/v2 document gains a per-entrypoint `keyDiff`
                  field. Off by default.
  --explain-miss-verbose
                  Like --explain-miss, but shows full untruncated component
                  values instead of the terse truncated form. Implies
                  --explain-miss.
  --no-remote-cache
                  Drop every configured `remote-cache` tier for this run.
                  The local ("l1") cache stays active -- this is strictly
                  weaker than --no-cache, which disables caching entirely.
                  Useful for a one-off run when a shared tier is unreachable
                  or you want to bypass it without editing crisol.kdl. No
                  KDL equivalent (a config-file remote-cache block describes
                  what a fleet should use, not a one-run override). Off by
                  default.
  --cache-stats   Print a one-line cache-hit/miss/publish/wall-time-saved
                  summary after the run (also settable via crisol.kdl's
                  `cache-stats #true`) and add a `cacheStats` object to the
                  run/v2 JSON document. In --json mode the summary line
                  renders to stderr (stdout stays parseable JSON). Also
                  enables a stderr warning when a cache tier errored on
                  every read consulted this run (a misconfigured/dead
                  tier, indistinguishable otherwise from a cold cache).
                  Off by default (no telemetry sink installed).
  --verify-cache  The determinism backstop: after the run completes, re-
                  executes a sample of this run's cache hits and compares
                  the fresh observation against the stored one. Divergence
                  is never silent — a stderr warning names the entrypoint
                  and the JSON `verifyFails` count reflects it. Never
                  evicts. Off by default.
  --verify-cache-pct N
                  Sample size as a percentage of this run's cache hits
                  (default 5, or crisol.kdl's `verify-cache-pct`).
                  Requires --verify-cache.
  --verify-cache-seed N
                  Pins the sampler's seed for a reproducible sample
                  (default: a per-run value). Requires --verify-cache.
  --verify-cache-strict
                  A divergence found by the pass sets the process exit
                  code to 1 (CI gate) in addition to the stderr warning.
                  Requires --verify-cache.

Additional options for 'list':
  --json          Emit the crisol/plan/v1 JSON document instead of human output.

Options for 'closure':
  <entrypoint>... Show the recorded depgraph entry for one or more planned
                  paths (repeatable).  Mutually exclusive with --all
                  (specifying both is a usage error); one of the two is
                  required.  A path matching no discovered entrypoint at all
                  is a configuration error (exit 3), same as `run`.  A path
                  whose only match was discovered but gated out prints an
                  empty report and exits 0, also same as `run`.
  --all           Show every discovered entrypoint, one crisol/closure/v1
                  document.  Discovery gates still apply: this is the same
                  set `crisol list --all-groups` would show — a gated-out
                  entrypoint is not listed (and --all with zero discovered
                  entrypoints is not an error; it prints an empty report).
  --json          Emit the crisol/closure/v1 JSON document instead of human
                  output.
  --config <path> Use this config file instead of walking up from the
                  current directory for crisol.kdl.
  Each entry's `closure` paths are project-root-relative (forward slashes)
  for in-root files, and absolute for files under a configured dep-root.

Exit codes:
  0   All selected entrypoints passed (or a pure listing succeeded).
  1   One or more entrypoints failed / compile-failed / timed-out / signaled.
  2   Crisol internal error (should not occur in normal operation).
  3   Environment / configuration error (bad args, no entrypoints found, etc.).
"""

# ---------------------------------------------------------------------------
# Color decision: pure helper + isatty wrapper
# ---------------------------------------------------------------------------

proc computeColorEnabled(): bool =
  ## Returns true iff stdout is a TTY AND NO_COLOR is unset.
  let tty = stdterm.isatty(stdout)
  shouldEnableColor(tty)

type ConfigFlagOutcome = enum
  cfoNotConfigFlag  ## `args[ci]` is not a `--config` flag at all — left
                     ## completely untouched (`dest`/`ci` unchanged); the
                     ## caller's other-flag handling runs in this case.
  cfoTaken          ## `args[ci]` was `--config`/`--config=...` and `dest`
                     ## was set.
  cfoMissingValue    ## `args[ci]` was `--config`/`--config=` with a missing
                     ## or empty value — the "--config requires a file path"
                     ## error has already been written to stderr.

proc takeConfigFlag(args: seq[string]; ci: var int; dest: var string): ConfigFlagOutcome =
  ## Recognizes AND parses `--config <path>` / `--config=<path>` at
  ## `args[ci]`, owning the whole branch (match condition, value extraction,
  ## and the "--config requires a file path" error) so call sites don't
  ## repeat any of it.
  ##
  ## For the space-separated form, advances `ci` past the consumed value
  ## token (so the caller's enclosing `while` loop's `inc ci` lands past it,
  ## same as before this helper existed).
  let a = args[ci]
  if a == "--config":
    inc ci
    if ci >= args.len:
      stderr.write("crisol: --config requires a file path\n")
      return cfoMissingValue
    dest = args[ci]
    return cfoTaken
  elif a.startsWith("--config="):
    let v = a[9..^1]   # strip "--config="
    if v == "":
      stderr.write("crisol: --config requires a file path\n")
      return cfoMissingValue
    dest = v
    return cfoTaken
  else:
    return cfoNotConfigFlag

proc writeStderr(text: string) =
  ## Sanitizes `text` (ioutils.sanitizeControlBytes — the one shared
  ## primitive, also used by depgraph's header-field formatter) and writes it
  ## plus a trailing newline to stderr.  This is the ONE write path for user-facing error/diagnostic
  ## text that may embed untrusted-origin content: `CrisolError.msg` (config
  ## errors legitimately embed nkdl's multi-line caret block —
  ## sanitizeControlBytes preserves '\n' so that block's line structure
  ## survives), `RunReport.error`, gate-skip lines, junit-write error
  ## messages, path-flag warnings, and `ConfigWarning.message`.
  stderr.write(sanitizeControlBytes(text) & "\n")

proc writeStdout(text: string) =
  ## Same as `writeStderr` but for stdout — used for gate-skip lines, which
  ## `run` has always emitted on stdout and `closure` now matches (see
  ## CHANGELOG: gate-skip lines moved from stderr to stdout for `closure`).
  stdout.write(sanitizeControlBytes(text) & "\n")

proc writeWarnings(ws: seq[ConfigWarning]) =
  ## Convenience: writes each ConfigWarning's message to stderr as
  ## "warning: <msg>", routed through `writeStderr`.
  for w in ws:
    writeStderr("warning: " & w.message)

# ---------------------------------------------------------------------------
# runMain — testable entry; returns the process exit code
# ---------------------------------------------------------------------------

proc runMain*(args: seq[string]; selfWorkerBinary: string = ""): int =
  ## Parse `args` (argv without the program name), execute the pipeline,
  ## and return the exit code.  Does NOT call quit().
  ##
  ## `selfWorkerBinary` becomes `RunOptions.workerBinary` (see below) and
  ## therefore the self-reexec target for RFC-0006's measureCompileReuse
  ## compile-slot worker.  It defaults to "" (no
  ## worker) rather than resolving `getAppFilename()` itself, because
  ## `getAppFilename()` returns whatever process is CURRENTLY RUNNING —
  ## sound only when that process is genuinely the crisol CLI binary (which
  ## dispatches InternalMeasureCompileToken,
  ## below).  `runMain` is also called IN-PROCESS by crisol's own test
  ## suite and by any library embedder that links against `crisol` as a
  ## module — for those callers `getAppFilename()` would point at the TEST
  ## or HOST binary, whose entrypoint does NOT dispatch either internal
  ## token, so a self-reexec would just re-run that whole program (unsound,
  ## up to an unbounded recursive fork). The real CLI binary's own
  ## `when isMainModule` entrypoint (bottom of this file) is the ONLY
  ## caller that passes `getAppFilename()` here — it alone can prove it IS
  ## that sound target. Every other caller gets the safe default: an empty
  ## workerBinary degrades spawnCompileStable to the monolithic compile
  ## path (see runner.nim / types.Config.workerBinary's own doc).

  if args.len == 0:
    stderr.write(usage())
    return ExitEnvironment

  let sub = args[0]

  if sub in ["-h", "--help"]:
    stdout.write(usage())
    return ExitOk

  if sub in ["--version", "-V", "version"]:
    stdout.write("crisol " & CrisolVersion & "\n")
    return ExitOk

  # RFC-0006 M-artifact-identity (pass (b1)): the internal measurement-worker
  # re-exec surface (`crisol --internal-measure-compile <plan.json>`).
  # Deliberately routed here, before subcommand validation, and NOT listed in
  # usage() — this is an internal re-exec token, not a user-facing
  # subcommand. See crisol/measureworker.nim for the worker pipeline.
  if sub == InternalMeasureCompileToken:
    if args.len < 2:
      stderr.write("crisol: " & InternalMeasureCompileToken &
                   " requires a <plan.json> path\n")
      return ExitEnvironment
    return runMeasureCompileWorker(args[1])

  if sub notin ["run", "list", "clean", "init", "closure"]:
    stderr.write("crisol: unknown subcommand '" & sub & "'\n\n")
    stderr.write(usage())
    return ExitEnvironment

  let isList  = sub == "list"
  let isClean = sub == "clean"

  # -------------------------------------------------------------------------
  # `clean` subcommand: orphan pruning (+ --all).
  # Handled early, before the shared run/list flag parser.
  # -------------------------------------------------------------------------

  if isClean:
    var doCleanAll    = false
    var cleanCfgPath  = ""
    let cleanArgs = args[1..^1]
    var ci = 0
    while ci < cleanArgs.len:
      let a = cleanArgs[ci]
      case takeConfigFlag(cleanArgs, ci, cleanCfgPath)
      of cfoTaken: discard
      of cfoMissingValue: return ExitEnvironment
      of cfoNotConfigFlag:
        if a == "--all":
          doCleanAll = true
        else:
          stderr.write("crisol: unknown flag for clean: '" & a & "'\n")
          return ExitEnvironment
      inc ci

    let (cfg, _) = loadConfig(configPath = cleanCfgPath)
    let stateDir = stateDirOf(cfg)

    if doCleanAll:
      # --all: remove the whole state dir — no lock needed.
      try:
        cleanAll(cfg)
      except Exception as e:
        writeStderr("crisol: clean --all failed: " & e.msg)
        return ExitInternal
      return ExitOk

    # Acquire the lock before mutating shared state.
    var lockHandle: LockHandle
    try:
      lockHandle = acquireLock(stateDir)
    except CrisolError as e:
      writeStderr("crisol: " & e.msg)
      return ExitEnvironment

    defer: releaseLock(lockHandle)

    try:
      # RFC-0006 nimcache-persistence GC: real toolchain probe so cache/
      # pruning correctly orphans dirs left over from an old cc/nim
      # fingerprint (see cleanOrphans' doc). nimVersion uses the RUNTIME
      # nim fingerprint (nimprobe.cachedNimFingerprint), not crisolNimVersion —
      # same soundness rule as api.nim's cache-identity feeds.
      let r = cleanOrphans(cfg, nimVersion = cachedNimFingerprint(), ccVersion = cachedCcVersion())
      stdout.write("crisol clean: pruned " & $r.cacheDeleted &
                   " cache dir(s), " & $r.binDeleted &
                   " bin dir(s), " & $r.graphEntriesDropped &
                   " depgraph entry(ies); evicted " & $r.cacheEvicted &
                   " result-cache entry(ies); compacted " &
                   $r.shardsRemoved & " ledger shard(s) (" &
                   $r.ledgerRowsKept & " row(s) kept); compacted " &
                   $r.artifactReport.shardsRemoved & " artifact shard(s) (" &
                   $r.artifactReport.rowsKept & " row(s) kept); compacted " &
                   $r.compileCostReport.shardsRemoved & " compile-cost shard(s) (" &
                   $r.compileCostReport.rowsKept & " row(s) kept)\n")
    except CrisolError as e:
      writeStderr("crisol: clean error: " & e.msg)
      return ExitEnvironment
    except Exception as e:
      writeStderr("crisol: clean unexpected error: " & e.msg)
      return ExitInternal

    return ExitOk

  # -------------------------------------------------------------------------
  # `init` subcommand: write canonical starter crisol.kdl.
  # -------------------------------------------------------------------------

  if sub == "init":
    var targetPath = "crisol.kdl"   # default: crisol.kdl in cwd
    var forceInit  = false
    let initArgs = args[1..^1]
    var ii = 0
    while ii < initArgs.len:
      let a = initArgs[ii]
      if a == "--force":
        forceInit = true
      elif a.startsWith("-"):
        stderr.write("crisol: unknown flag for init: '" & a & "'\n")
        return ExitEnvironment
      else:
        targetPath = a
      inc ii

    let absTarget = if isAbsolute(targetPath): targetPath
                    else: getCurrentDir() / targetPath

    # ioutils.writeGuardedFile: single atomic open() — no TOCTOU, no symlink
    # follow-through (RFC-0007 A3).
    #
    # noFollow=true: refuse to follow a symlink at the final path component
    #                on every branch, including --force (no write-through).
    # overwrite=false (not forceInit): O_EXCL — atomically refuse if
    #                ANYTHING already exists.
    # overwrite=true  (forceInit):     O_TRUNC — truncate an existing
    #                regular file.
    # Mode 0o644: owner rw, group r, other r.
    let (writeOk, writeErr, alreadyExists) =
      ioutils.writeGuardedFile(absTarget, InitTemplate, 0o644, overwrite = forceInit)

    if not writeOk:
      if alreadyExists:
        # Set on EEXIST (file exists and --force not given, O_EXCL
        # triggered) or ELOOP (O_NOFOLLOW caught a symlink, both with and
        # without --force).
        stderr.write("crisol: init: '" & absTarget & "' already exists; " &
                     "use --force to overwrite\n")
      else:
        stderr.write("crisol: init: cannot write '" & absTarget & "': " &
                     writeErr & "\n")
      return ExitEnvironment

    stdout.write("crisol: init: wrote " & absTarget & "\n")
    return ExitOk

  # -------------------------------------------------------------------------
  # `closure` subcommand: issue #9 slice A — read-only depgraph projection.
  # Handled early, before the shared run/list flag parser: closure has its
  # own minimal flag set (positional <entrypoint> XOR --all, plus --json)
  # and shares NONE of run/list's tuning flags.
  # -------------------------------------------------------------------------

  if sub == "closure":
    var closurePaths: seq[string]
    var closureAll   = false
    var closureJson  = false
    var closureCfgPath = ""   # --config <path> / --config=<path>
    let closureArgs = args[1..^1]
    var ci = 0
    while ci < closureArgs.len:
      let a = closureArgs[ci]
      case takeConfigFlag(closureArgs, ci, closureCfgPath)
      of cfoTaken: discard
      of cfoMissingValue: return ExitEnvironment
      of cfoNotConfigFlag:
        if a == "--all":
          closureAll = true
        elif a == "--json":
          closureJson = true
        elif a.startsWith("-"):
          stderr.write("crisol: unknown flag for closure: '" & a & "'\n")
          return ExitEnvironment
        else:
          closurePaths.add a
      inc ci

    if closureAll and closurePaths.len > 0:
      stderr.write("crisol: 'closure' accepts either <entrypoint> or --all, " &
                   "not both\n\n")
      stderr.write(usage())
      return ExitEnvironment

    if not closureAll and closurePaths.len == 0:
      stderr.write("crisol: closure requires <entrypoint> or --all\n\n")
      stderr.write(usage())
      return ExitEnvironment

    let closureSelection =
      if closureAll: allGroups()
      else: filesSelection(closurePaths)

    var cr: ClosureReport
    try:
      cr = closureReport(RunOptions(selection: closureSelection,
                                    configPath: closureCfgPath))
    except CrisolError as e:
      case e.kind
      of cekEnvironment:
        writeStderr("crisol: environment error: " & e.msg)
        return ExitEnvironment
      of cekConfig:
        writeStderr("crisol: config error: " & e.msg)
        return ExitEnvironment
      of cekInternal:
        writeStderr("crisol: internal error: " & e.msg)
        return ExitInternal

    writeWarnings(cr.warnings)

    # Issue #3 / RFC-0001:409: warn about ad-hoc gskFiles paths, same as
    # run/list.  closure has no --group flag, so withinGroups is always
    # empty here.
    for line in pathFlagsWarnings(cr.adHocPaths, @[]):
      writeStderr("crisol: " & line)

    # A positional <entrypoint>... selection that matched no discovered
    # entrypoint at all is a configuration error, same as `run` (exit 3).
    # A selection whose only match(es) were discovered but GATED OUT is
    # NOT that case — it lands in cr.gatedOut, not cr.entries — and `run`
    # exits 0 for the identical selection (zrkAllGated); `closure` matches
    # that contract: print the (empty-entries) report and exit 0.  `--all`
    # with zero discovered entrypoints is likewise NOT an error (an empty
    # report is a legitimate answer to "what's discovered").
    if not closureAll and cr.entries.len == 0 and cr.gatedOut.len == 0:
      stderr.write("crisol: no entrypoints matched — check config/globs\n")
      return ExitEnvironment

    if closureJson:
      stdout.write(closureToJsonString(cr))
      stdout.write("\n")
    else:
      # Mirror `run`'s zrkAllGated case: renderClosure only walks .entries,
      # so an all-gated selection would otherwise print nothing at all in
      # human mode.  Print the gate-skip lines on STDOUT (matching `run`'s
      # placement — see CHANGELOG) before the (possibly empty) report;
      # JSON mode above is unaffected (nothing but the JSON document on
      # stdout).
      for line in gateSkipMessages(cr.gatedOut):
        writeStdout(line)
      stdout.write(renderClosure(cr))
    return ExitOk

  # -------------------------------------------------------------------------
  # Parse flags (run + list share most; run adds jobs/timeout/fail-fast/dry-run)
  # -------------------------------------------------------------------------

  var
    paths:        seq[string]
    groupNames:   seq[string]   # collected from --group (repeatable)
    allGroups:    bool = false  # set by --all-groups
    configPath:   string = ""   # C1: --config <path> override
    jobs:         int  = 0
    timeout:      int  = 0
    failFast:     bool = false
    jsonMode:     bool = false
    dryRun:       bool = false
    useFailed:    bool = false
    useChanged:   bool = false  # D5: impact selection via git diff
    baseRef:      string = ""   # D5: --base <ref>; "" means diff vs HEAD
    forceCompile: bool = false
    noCache:      bool = false  # A9: --no-cache: do NOT read/write the result cache
    noRemoteCache: bool = false # RFC-0005 A3c-ii: --no-remote-cache: drop configured
                                 # remote-cache tiers; l1 stays active
    filterTag:    string = ""   # C3: reporting-level record filter
    retries:      int  = -1     # B1: --retries N; -1 = not specified (use config)
    failOnFlaky:  bool = false  # B1: --fail-on-flaky: flaky-passes → exit 1
    strictHygiene: bool = false # rfc-0007 A6b: --strict-hygiene: escapee-bearing
                                 # passes → exit 1
    junitPath:    string = ""   # C1: --junit <path> JUnit XML report output path
    shardK:       int  = 0      # C2: shard index (1-indexed); 0 = no sharding
    shardN:       int  = 1      # C2: total shard count; only used when shardK > 0
    orderMode:    OrderMode = omNone  # C4: history-based prioritization
    perfCheck:    bool = false  # C6: --perf-check: force perf-regression detection ON
    hermeticLevel: HermeticLevel = hlIsolated  # RFC-0004: --hermetic none|isolated|network
    measureCompileReuse: bool = false  # RFC-0006: --measure-compile-reuse: gate the
                                        # measurement worker into the compile slot
    rlimitNofile: int = 0        # Fix 1: --rlimit-nofile N; 0 = not specified (use config/built-in)
    verifyCache:       bool = false  # RFC-0005 B3c: --verify-cache: enable the post-run pass
    verifyCachePctFlag: int  = 0     # --verify-cache-pct N; 0 = not specified (use config/built-in)
    verifyCacheSeed:   Option[int64] = none(int64)  # --verify-cache-seed N
    verifyCacheStrict: bool = false  # --verify-cache-strict: a divergence flips the exit code
    envPins: seq[(string, string)]   # RFC-0005 A0: collected from --env-pin NAME=VALUE (repeatable)
    explainMissFlag:        bool = false  # RFC-0005 B1c: --explain-miss
    explainMissVerboseFlag: bool = false  # RFC-0005 B1c: --explain-miss-verbose (implies explain)
    cacheStatsFlag:         bool = false  # RFC-0005 B2b: --cache-stats

  let runArgs = args[1..^1]
  var i = 0
  while i < runArgs.len:
    let a = runArgs[i]
    if a.startsWith("--"):
      let flagBody = a[2..^1]
      var key = flagBody
      var valInline = ""
      var hasInline = false
      let eq = flagBody.find('=')
      if eq >= 0:
        key = flagBody[0..<eq]
        valInline = flagBody[eq+1..^1]
        hasInline = true

      proc nextVal(name: string): string =
        if hasInline: return valInline
        if i + 1 < runArgs.len and not runArgs[i+1].startsWith("-"):
          inc i
          return runArgs[i]
        stderr.write("crisol: --" & name & " requires a value\n")
        return ""

      # Flags valid only for `run`.
      if key in ["jobs", "timeout", "fail-fast", "dry-run", "failed", "changed",
                 "base", "force-compile", "no-cache", "filter-tag",
                 "retries", "fail-on-flaky", "strict-hygiene", "junit", "shard", "order",
                 "perf-check", "hermetic", "measure-compile-reuse",
                 "rlimit-nofile", "verify-cache", "verify-cache-pct",
                 "verify-cache-seed", "verify-cache-strict", "env-pin",
                 "explain-miss", "explain-miss-verbose", "cache-stats",
                 "no-remote-cache"] and isList:
        stderr.write("crisol: '--" & key & "' is not valid for 'list'\n\n")
        stderr.write(usage())
        return ExitEnvironment

      case key
      of "config":
        let raw = nextVal("config")
        if raw == "":
          stderr.write("crisol: --config requires a file path\n")
          return ExitEnvironment
        configPath = raw
      of "group":
        let raw = nextVal("group")
        if raw == "":
          stderr.write("crisol: --group requires a group name\n")
          return ExitEnvironment
        groupNames.add raw
      of "all-groups":
        allGroups = true
      of "jobs":
        let raw = nextVal("jobs")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          jobs = parseInt(raw)
          if jobs < 1:
            stderr.write("crisol: --jobs must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --jobs: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "timeout":
        let raw = nextVal("timeout")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          timeout = parseInt(raw)
          if timeout < 1:
            stderr.write("crisol: --timeout must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --timeout: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "fail-fast":
        failFast = true
      of "dry-run":
        dryRun = true
      of "json":
        jsonMode = true
      of "failed":
        useFailed = true
      of "changed":
        useChanged = true
      of "base":
        let raw = nextVal("base")
        if raw == "":
          stderr.write("crisol: --base requires a git ref\n")
          return ExitEnvironment
        baseRef = raw
      of "force-compile":
        forceCompile = true
      of "no-cache":
        noCache = true
      of "no-remote-cache":
        noRemoteCache = true
      of "retries":
        let raw = nextVal("retries")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          retries = parseInt(raw)
          if retries < 0:
            stderr.write("crisol: --retries must be >= 0\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --retries: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "fail-on-flaky":
        failOnFlaky = true
      of "strict-hygiene":
        strictHygiene = true
      of "junit":
        let raw = nextVal("junit")
        if raw == "":
          stderr.write("crisol: --junit requires a file path\n")
          return ExitEnvironment
        junitPath = raw
      of "filter-tag":
        let raw = nextVal("filter-tag")
        if raw == "":
          stderr.write("crisol: --filter-tag requires a tag name\n")
          return ExitEnvironment
        filterTag = raw
      of "shard":
        let raw = nextVal("shard")
        if raw == "":
          stderr.write("crisol: --shard requires a k/n value (e.g. --shard 1/3)\n")
          return ExitEnvironment
        try:
          let parsed = parseShardSpec(raw)
          shardK = parsed.k
          shardN = parsed.n
        except ValueError as e:
          stderr.write("crisol: " & e.msg & "\n")
          return ExitEnvironment
      of "order":
        let raw = nextVal("order")
        if raw == "":
          stderr.write("crisol: --order requires a mode (recent-fail, duration, none)\n")
          return ExitEnvironment
        try:
          orderMode = parseOrderMode(raw)
        except ValueError as e:
          stderr.write("crisol: " & e.msg & "\n")
          return ExitEnvironment
      of "perf-check":
        perfCheck = true
      of "measure-compile-reuse":
        measureCompileReuse = true
      of "hermetic":
        let raw = nextVal("hermetic")
        if raw == "":
          stderr.write("crisol: --hermetic requires a level (none, isolated, network)\n")
          return ExitEnvironment
        case raw
        of "none":     hermeticLevel = hlNone
        of "isolated": hermeticLevel = hlIsolated
        of "network":  hermeticLevel = hlNetwork
        else:
          stderr.write("crisol: --hermetic: invalid level '" & raw &
                       "' (expected none, isolated, or network)\n")
          return ExitEnvironment
      of "rlimit-nofile":
        let raw = nextVal("rlimit-nofile")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          rlimitNofile = parseInt(raw)
          if rlimitNofile < 1:
            stderr.write("crisol: --rlimit-nofile must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --rlimit-nofile: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "verify-cache":
        verifyCache = true
      of "verify-cache-pct":
        let raw = nextVal("verify-cache-pct")
        if raw == "":
          stderr.write("crisol: --verify-cache-pct requires an integer value\n")
          return ExitEnvironment
        try:
          verifyCachePctFlag = parseInt(raw)
          if verifyCachePctFlag < 1:
            stderr.write("crisol: --verify-cache-pct must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --verify-cache-pct: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "verify-cache-seed":
        let raw = nextVal("verify-cache-seed")
        if raw == "":
          stderr.write("crisol: --verify-cache-seed requires an integer value\n")
          return ExitEnvironment
        try:
          verifyCacheSeed = some(int64(parseBiggestInt(raw)))
        except ValueError:
          stderr.write("crisol: --verify-cache-seed: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "verify-cache-strict":
        verifyCacheStrict = true
      of "explain-miss":
        explainMissFlag = true
      of "explain-miss-verbose":
        # verbose implies explain (single-flag-answer: --explain-miss-verbose
        # alone is enough to get output).
        explainMissFlag = true
        explainMissVerboseFlag = true
      of "cache-stats":
        cacheStatsFlag = true
      of "env-pin":
        # RFC-0005 A0: --env-pin NAME=VALUE (repeatable). Malformed input
        # (no '=', or an empty NAME) is a usage error, same shape as --base
        # requiring --changed.
        let raw = nextVal("env-pin")
        if raw == "":
          stderr.write("crisol: --env-pin requires a NAME=VALUE argument\n")
          return ExitEnvironment
        let eqIdx = raw.find('=')
        if eqIdx < 0:
          stderr.write("crisol: --env-pin: expected NAME=VALUE, got '" &
                       raw & "' (missing '=')\n")
          return ExitEnvironment
        let pinName = raw[0 ..< eqIdx]
        let pinValue = raw[eqIdx + 1 .. ^1]
        if pinName.len == 0:
          stderr.write("crisol: --env-pin: NAME must not be empty (got '" &
                       raw & "')\n")
          return ExitEnvironment
        envPins.add (pinName, pinValue)
      else:
        stderr.write("crisol: unknown flag '--" & key & "'\n\n")
        stderr.write(usage())
        return ExitEnvironment
    elif a.startsWith("-") and a.len > 1:
      let key = a[1..^1]
      proc nextVal2(name: string): string =
        if i + 1 < runArgs.len and not runArgs[i+1].startsWith("-"):
          inc i
          return runArgs[i]
        stderr.write("crisol: -" & name & " requires a value\n")
        return ""
      if key in ["j", "t"] and isList:
        stderr.write("crisol: '-" & key & "' is not valid for 'list'\n\n")
        stderr.write(usage())
        return ExitEnvironment
      case key
      of "j":
        let raw = nextVal2("j")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          jobs = parseInt(raw)
          if jobs < 1:
            stderr.write("crisol: --jobs must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --jobs: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "t":
        let raw = nextVal2("t")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          timeout = parseInt(raw)
          if timeout < 1:
            stderr.write("crisol: --timeout must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --timeout: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      else:
        stderr.write("crisol: unknown flag '-" & key & "'\n\n")
        stderr.write(usage())
        return ExitEnvironment
    else:
      paths.add a
    inc i

  # -------------------------------------------------------------------------
  # Build config and apply CLI overrides
  # -------------------------------------------------------------------------

  # --group and --all-groups are mutually exclusive: they are semantically
  # contradictory (named subset vs. full set), so we error rather than silently
  # picking a winner.
  if groupNames.len > 0 and allGroups:
    stderr.write("crisol: --group and --all-groups are mutually exclusive\n\n")
    stderr.write(usage())
    return ExitEnvironment

  let colorEnabled = computeColorEnabled()

  # Build GroupSelection from parsed flags.
  #
  # Issue #3 / RFC-0001:409: paths and --group are NOT mutually exclusive — a
  # path narrows WHICH files run, --group narrows WHICH configured groups are
  # candidate owners for those paths.  withinGroups carries --group through so
  # discover() still validates/attributes against the named group(s) instead
  # of silently dropping --group whenever a path is also given.
  var selection: GroupSelection
  if paths.len > 0:
    selection = GroupSelection(kind: gskFiles, paths: paths, withinGroups: groupNames)
  elif allGroups:
    selection = GroupSelection(kind: gskAll)
  elif groupNames.len > 0:
    selection = GroupSelection(kind: gskNamed, names: groupNames)
  else:
    selection = GroupSelection(kind: gskDefault)

  # --base without --changed is a CLI error (exit 3): --base is meaningless
  # without narrowing and silently ignoring it would always be a mistake.
  if baseRef.len > 0 and not useChanged:
    stderr.write("crisol: error: --base requires --changed " &
                 "(a base ref without impact selection has no effect)\n")
    return ExitEnvironment

  # RFC-0005 B3c: each --verify-cache-* PARAMETER flag requires --verify-cache
  # itself — same shape as --base requiring --changed above (a parameter
  # without the pass it configures has no effect and is always a mistake).
  if verifyCachePctFlag > 0 and not verifyCache:
    stderr.write("crisol: error: --verify-cache-pct requires --verify-cache\n")
    return ExitEnvironment
  if verifyCacheSeed.isSome and not verifyCache:
    stderr.write("crisol: error: --verify-cache-seed requires --verify-cache\n")
    return ExitEnvironment
  if verifyCacheStrict and not verifyCache:
    stderr.write("crisol: error: --verify-cache-strict requires --verify-cache\n")
    return ExitEnvironment

  # RFC-0005 B3c: resolve the sample percentage. --verify-cache-pct (when
  # given) always wins; otherwise fall back to the config file's
  # `verify-cache-pct` (defaulting to config.DefaultVerifyCachePct when the
  # KDL node itself is absent). This is a SECOND, lightweight loadConfig
  # call, deliberately scoped to just this one field — mirrors the `clean`
  # subcommand's own early loadConfig above, and keeps this slice's touched
  # surface to crisol.nim/config.nim/jsonout.nim (the actual pipeline load
  # inside runTests/planTests, below, still owns the real Config used to
  # run). A library caller going through crisol/api directly (not this CLI)
  # does not get this config-file fallback — verifySample()'s own default
  # (5) applies instead; documented on VerifyCache/RunOptions in api.nim.
  var verifyCachePctResolved = verifyCachePctFlag
  if verifyCache and verifyCachePctFlag == 0:
    try:
      let (cfgPeek, _) = loadConfig(configPath = configPath)
      verifyCachePctResolved = cfgPeek.verifyCachePct
    except CrisolError as e:
      case e.kind
      of cekEnvironment:
        writeStderr("crisol: environment error: " & e.msg)
        return ExitEnvironment
      of cekConfig:
        writeStderr("crisol: config error: " & e.msg)
        return ExitEnvironment
      of cekInternal:
        writeStderr("crisol: internal error: " & e.msg)
        return ExitInternal

  let verifyCacheOpts =
    if verifyCache: verifySample(pct = verifyCachePctResolved, seed = verifyCacheSeed,
                                 strict = verifyCacheStrict)
    else: noVerify()

  # Build narrowing.
  var narrowing: RunNarrowing
  if useFailed and useChanged:
    narrowing = failedOrChanged(baseRef)
  elif useChanged:
    narrowing = changedOnly(baseRef)
  elif useFailed:
    narrowing = failedOnly()
  else:
    narrowing = noNarrowing()

  let opts = RunOptions(
    configPath:          configPath,
    selection:           selection,
    narrowing:           narrowing,
    forceCompile:        forceCompile,
    failFast:            failFast,
    noCache:             noCache,
    noRemoteCache:       noRemoteCache, # RFC-0005 A3c-ii: --no-remote-cache
    jobs:                jobs,
    timeoutSecs:         timeout,
    showProgress:        not jsonMode,
    progressIntervalMs:  30_000,
    manageLock:          true,
    installSignals:      true,
    persist:             true,
    retries:             retries,       # B1: -1 = use config; >= 0 = override
    failOnFlaky:         failOnFlaky,   # B1: flaky-pass → exit 1
    strictHygiene:       strictHygiene, # rfc-0007 A6b: escapee-bearing pass → exit 1
    shardK:              shardK,        # C2: shard index (0 = no sharding)
    shardN:              shardN,        # C2: total shard count
    order:               orderMode,     # C4: history-based prioritization
    perfCheckForce:      perfCheck,     # C6: --perf-check: force detection ON
    hermeticLevel:       hermeticLevel, # RFC-0004: --hermetic level control
    rlimitNofile:        if rlimitNofile > 0: some(int64(rlimitNofile)) else: none(int64),
                                         # Fix 1: --rlimit-nofile override
    measureCompileReuse: measureCompileReuse,  # RFC-0006: gate measurement worker into compile slot
    verifyCache:         verifyCacheOpts,  # RFC-0005 B3c: --verify-cache facade
    envPins:             envPins,       # RFC-0005 A0: --env-pin NAME=VALUE (repeatable)
    explainMiss:         explainMissFlag,         # RFC-0005 B1c: verbose already folded in above
    explainMissVerbose:  explainMissVerboseFlag,  # RFC-0005 B1c
    cacheStats:          cacheStatsFlag,          # RFC-0005 B2b
    workerBinary:        selfWorkerBinary,  # "" unless the real CLI entrypoint (below) passed
                                             # its own getAppFilename() — see runMain's doc above
                                             # for why this must never be resolved in here.
  )

  # -------------------------------------------------------------------------
  # `list` and `run --dry-run`: pure plan phase; no lock, no subprocess.
  # -------------------------------------------------------------------------

  if isList or dryRun:
    var pr: PlanReport
    try:
      pr = planTests(opts)
    except CrisolError as e:
      case e.kind
      of cekEnvironment:
        writeStderr("crisol: environment error: " & e.msg)
        return ExitEnvironment
      of cekConfig:
        writeStderr("crisol: config error: " & e.msg)
        return ExitEnvironment
      of cekInternal:
        writeStderr("crisol: internal error: " & e.msg)
        return ExitInternal

    # Emit config warnings.
    writeWarnings(pr.warnings)

    # Issue #3 / RFC-0001:409: warn about ad-hoc gskFiles paths.
    for line in pathFlagsWarnings(pr.adHocPaths, groupNames):
      writeStderr("crisol: " & line)

    if jsonMode:
      stdout.write(planToJsonString(pr, substrate = process.capabilities()))
      stdout.write("\n")
    else:
      let ropts = RenderOpts(color: colorEnabled, slowestN: 5)
      stdout.write(renderPlan(pr, ropts))
    return ExitOk

  # -------------------------------------------------------------------------
  # `run`: full execution via runTests.
  # -------------------------------------------------------------------------

  let rr = runTests(opts)

  # Emit config warnings to stderr.
  writeWarnings(rr.plan.warnings)

  # Issue #3 / RFC-0001:409: warn about ad-hoc gskFiles paths.
  for line in pathFlagsWarnings(rr.plan.adHocPaths, groupNames):
    writeStderr("crisol: " & line)

  if rr.status == rsStructural:
    writeStderr("crisol: " & rr.error)
    return rr.exitCode

  # rfc-0007 A1e-ii: the old early return here (`rsInterrupted -> return
  # rr.exitCode`, skipping stdout entirely) is RETIRED — that was the second
  # of the two discard points this slice closes. An interrupted run now
  # falls through the SAME reporting path as a normal one: rr.results/
  # rr.summary already carry §2's honest partial emission set, so the JSON/
  # render/junit writers below need no special-casing beyond threading
  # rr.interrupted into the wire (see the --json branch below).

  # Zero-runnable exit-0 branches: rsOk with zero results.
  if rr.results.len == 0 and rr.status == rsOk:
    case rr.zeroRunnableReason
    of zrkChangedClean:
      stdout.write("crisol: nothing affected by the changes — nothing to run\n")
      return ExitOk
    of zrkFailedNone:
      stdout.write("crisol: no previously-failed entrypoints to re-run\n")
      return ExitOk
    of zrkAllGated:
      for line in gateSkipMessages(rr.plan.gatedOut):
        writeStdout(line)
      stdout.write("crisol: all groups gated out — nothing to run\n")
      return ExitOk
    of zrkNone:
      discard  # fall through to normal reporting

  # Fail-fast message.
  let totalPlanned = rr.plan.entrypoints.len
  if opts.failFast and rr.results.len < totalPlanned:
    let skipped = totalPlanned - rr.results.len
    stderr.write("crisol: fail-fast — stopped after first failure; " &
                 $skipped & " entrypoint(s) not started\n")

  # C3: zero-match warning.
  if filterTag.len > 0 and hasZeroTagMatches(rr.results, filterTag):
    stderr.write("crisol: warning: no test records matched tag \"" & filterTag & "\"\n")

  # rfc-0007 A6b: the resolved OutcomePolicy for this run (CLI flag OR
  # config-file, already merged by planImpl into rr.plan.settings) —
  # threaded into every REPORTING sink below so a per-entrypoint outcome
  # label never disagrees with rr.exitCode.
  let policy = OutcomePolicy(strictHygiene: rr.plan.settings.strictHygiene)

  # RFC-0005 B1c: resolved --explain-miss (CLI flag OR config-file
  # `explain-miss #true`, already merged by planImpl into rr.plan.settings)
  # -- threaded into both reporting sinks below so a config-file-only
  # opt-in (no CLI flag passed) is honored identically to the CLI flag.
  let explainMissResolved = rr.plan.settings.explainMiss

  # RFC-0005 B2b: resolved --cache-stats (CLI flag OR config-file
  # `cache-stats #true`, already merged by planImpl into rr.plan.settings)
  # -- same shape as explainMissResolved above.
  let cacheStatsResolved = rr.plan.settings.cacheStats

  if jsonMode:
    # In --json mode ALL human lines go to stderr (stdout stays parseable
    # JSON) -- the miss-explanation block is exactly such a human line; the
    # structured data lives in the `keyDiff` field below instead.
    if explainMissResolved:
      for r in rr.results:
        if isCacheMissDecision(r.cacheDecision):
          for blk in explainMissLines(r.keyDiff, explainMissVerboseFlag):
            for physLine in blk.splitLines():
              stderr.write("crisol: " & r.ep.path & ": explain: " & physLine & "\n")
    # RFC-0005 B2b: same routing rule -- the cache-stats summary line is
    # exactly such a human line; the structured data lives in the
    # `cacheStats` field below instead.
    if cacheStatsResolved:
      stderr.write("crisol: " & renderCacheStats(rr.cacheStats) & "\n")
    stdout.write(toJsonString(rr.results, rr.summary, filterTag, rr.plan.warnings,
                              rr.memThrottledSlots, interrupted = rr.interrupted,
                              policy = policy, substrate = process.capabilities(),
                              verifyFails = rr.verifyDivergences.len,
                              explainMiss = explainMissResolved,
                              cacheStats = rr.cacheStats,
                              showCacheStats = cacheStatsResolved))
    stdout.write("\n")
  else:
    let ropts = RenderOpts(color: colorEnabled, slowestN: 5,
                           filterTag: if filterTag.len > 0: some(filterTag)
                                      else: none(string),
                           explainMiss: explainMissResolved,
                           explainMissVerbose: explainMissVerboseFlag,
                           showCacheStats: cacheStatsResolved,
                           cacheStats: rr.cacheStats)
    stdout.write(render(rr.results, rr.summary, ropts, policy))
    # Gate-skip messages after results.
    if rr.plan.gatedOut.len > 0:
      for line in gateSkipMessages(rr.plan.gatedOut):
        writeStdout(line)

  # C1: --junit <path> — write JUnit XML report as an additional output sink.
  # Composes with normal stdout reporting (--json or human render still runs).
  if junitPath.len > 0:
    let xmlStr = toJunitXml(rr.results, rr.summary, policy)
    try:
      writeFile(junitPath, xmlStr)
    except IOError as e:
      writeStderr("crisol: warning: could not write junit report to '" &
                   junitPath & "': " & e.msg)
    except OSError as e:
      writeStderr("crisol: warning: could not write junit report to '" &
                   junitPath & "': " & e.msg)

  # RFC-0005 B3c: --verify-cache-strict — a divergence set is a CI-gate
  # failure. The pass never runs on a structural/interrupted return (both
  # already returned above), so rr.exitCode here is always the plain 0/1
  # from types.exitCode; strict only ever STRENGTHENS 0 -> 1, never masks
  # an already-nonzero code from an unrelated entrypoint failure.
  if opts.verifyCache.strict and rr.verifyDivergences.len > 0:
    return ExitTestFailure

  return rr.exitCode

# ---------------------------------------------------------------------------
# Binary entry point
# ---------------------------------------------------------------------------

when isMainModule:
  # This IS the real crisol CLI binary: it dispatches
  # InternalMeasureCompileToken (above, before
  # subcommand validation), so its own getAppFilename() is a sound
  # self-reexec target for RFC-0006's measurement compile-slot worker. This
  # is the ONLY call site allowed to pass a non-empty selfWorkerBinary — see
  # runMain's doc.
  let code = runMain(commandLineParams(), selfWorkerBinary = getAppFilename())
  # rfc-0007 A1e-ii: system.quit() SATURATES its argument to signed int8
  # range (-128..127) on POSIX before it ever reaches the real exit()
  # syscall (system.nim's own doc comment: "quit(int(0x100000000)) is equal
  # to quit(127) on Linux") — so `quit(130)`/`quit(143)` (RFC-0003's
  # SIGINT/SIGTERM 128+n codes) would silently both collapse to 127 on the
  # wire that actually reaches the parent process, discovered by this
  # slice's SIGINT/SIGTERM E2E (tests/timing/test_interrupt_e2e.nim) —
  # every exit code crisol ever produces below 128 is unaffected, so this
  # bypass is scoped to exactly the values that would otherwise be silently
  # wrong. exitnow (posix `_exit()`) skips Nim's exitprocs/GC-finalize
  # cleanup, so stdout/stderr are flushed explicitly first — everything
  # meaningful (the JSON/render output, junit file) is already written by
  # this point; there is nothing else exitprocs would need to do.
  if code > high(int8).int:
    stdout.flushFile()
    stderr.flushFile()
    exitnow(cint(code))
  else:
    quit(code)
