## crisol.nim — CLI entry point (A5 + B6 + B7 + C2 + C3)
##
## Thin shell: parse argv → apply overrides → wire pipeline → exit.
## No business logic lives here; all orchestration is in the library.
##
## Usage:
##   crisol run [<path>...]
##     --group <name>    run named group(s) instead of defaults (repeatable)
##     --all-groups      include opt-in groups (gates still apply)
##     --jobs <N>        parallel job cap (default: max(1, cpu-2))
##     --timeout <secs>  per-entrypoint run-timeout override
##     --fail-fast       stop launching new entrypoints on first failure
##     --dry-run         compute & print the plan; do NOT compile or run
##     --json            machine-readable output
##     --failed          re-run only entrypoints that failed in the last run
##     --filter-tag TAG  reporting-level filter: show only records tagged TAG;
##                       emits a warning to stderr when no records match
##   crisol list [<path>...] [--group <name>] [--all-groups]
##     --json            machine-readable plan output
##   crisol clean [--all]
##     --all             remove entire .crisol/ state dir (no lock needed)
##
## --group and --all-groups are mutually exclusive: specifying both is a usage
## error (exit 3).  Precedence: error is cleaner than silent last-wins because
## the two flags are semantically contradictory (named subset vs. full set).
##
## `list` and `run --dry-run` are the SAME pure plan phase (discover →
## applyGates → plan) with execution skipped — they share pipeline.buildRunPlan
## and emitPlan (CLI); neither spawns a subprocess.
##
## Exit codes (per RFC §CLI Surface):
##   0   all entrypoints passed (or a pure listing succeeded)
##   1   one or more entrypoints failed / compile-failed / timed-out / signaled
##   2   crisol internal error (should never occur in normal operation)
##   3   environment/configuration error: bad args, zero entrypoints discovered,
##       --failed with no prior run (lastrun.json absent)

import std/[options, os, strutils]
import std/posix
import crisol/[clean, terminal, api, config, lock, junit, shard, order, workerplan, measureworker, ccprobe, nimprobe]

# O_NOFOLLOW is a Linux extension not declared in Nim's std/posix.
# Pull it from <fcntl.h> via the emit+importc pattern.
{.emit: "#include <fcntl.h>".}
var O_NOFOLLOW_FLAG {.importc: "O_NOFOLLOW", nodecl.}: cint

# ---------------------------------------------------------------------------
# Exit codes (RFC §CLI Surface)
# ---------------------------------------------------------------------------

const
  ExitOk*          = 0
  ExitTestFailure* = 1
  ExitInternal*    = 2
  ExitEnvironment* = 3

# ---------------------------------------------------------------------------
# Version — parsed from crisol.nimble at compile time via staticRead.
# Works under both `nimble build` AND `nim r --path:src` (the project's own
# test bootstrap).  gorge/NimblePkgVersion are NOT used: gorge shells out at
# compile time and is fragile in sandboxed containers; NimblePkgVersion is only
# injected by nimble tasks, not by plain nim r.
# ---------------------------------------------------------------------------

const CrisolNimble = staticRead("../crisol.nimble")

func parseNimbleVersion(src: string): string =
  ## Extract the `version = "x.y.z"` line's value from a .nimble file.
  ## Returns "" if the line is absent or malformed.
  for line in src.splitLines():
    let s = line.strip()
    if s.startsWith("version") and s.len > 7 and s[7] in {' ', '\t', '='}:
      let eq = s.find('=')
      if eq < 0: continue
      var v = s[eq+1..^1].strip()
      if v.len >= 2 and v[0] == '"' and v[^1] == '"':
        return v[1..^2]
  return ""

const CrisolVersion* = parseNimbleVersion(CrisolNimble)

static:
  doAssert CrisolVersion.len > 0 and CrisolVersion[0] in {'0'..'9'},
    "crisol: failed to parse version from crisol.nimble — check the version = line"

# ---------------------------------------------------------------------------
# Init template — canonical starter crisol.kdl (S6).
# MUST use only known config keys so loadConfig parses it with zero warnings.
# ---------------------------------------------------------------------------

const InitTemplate* = """// crisol.kdl — canonical starter configuration
// Generated by `crisol init`.  Edit to suit your project.
// Reference: https://github.com/coreyleavitt/crisol  (see docs/rfc/0003-*)

// ---------------------------------------------------------------------------
// Global settings (all optional — defaults shown)
// ---------------------------------------------------------------------------

// jobs 0                    // 0 = auto (max(1, cpu_count - 2))
// timeout-secs 300          // per-entrypoint run timeout
// compile-timeout-secs 600  // per-entrypoint compile timeout
// max-output-bytes 10485760  // stdout+stderr cap per entrypoint

// State directory (relative to this file).  Change only if .crisol/ conflicts.
// state-dir ".crisol"

// ---------------------------------------------------------------------------
// Groups — at least one required
// ---------------------------------------------------------------------------

group "unit" {
    // Globs are relative to the project root (the directory containing this file).
    globs "tests/unit/test_*.nim"
}

// Opt-in group example: only runs when --all-groups or --group integration is passed.
// Remove or uncomment and customise as needed.
//
// group "integration" {
//     globs "tests/integration/test_*.nim"
//     opt-in #true
// }

// Gate example: run this group only when CI=true is set in the environment.
// Gates are evaluated at runtime; a closed gate skips the group (not an error).
//
// group "slow" {
//     globs "tests/slow/test_*.nim"
//     opt-in #true
//     gate "CI"
// }
"""

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------

proc usage(): string =
  """crisol — host-side test runner

Usage:
  crisol run  [<path>...] [--group <name>]... [--all-groups]
              [--jobs <N>] [--timeout <secs>] [--fail-fast]
              [--dry-run] [--json] [--force-compile]
              [--failed] [--changed [--base <ref>]]
              [--filter-tag <tag>]
              [--retries <N>] [--fail-on-flaky]
              [--order <recent-fail|duration|none>]
              [--hermetic <none|isolated|network>]
              [--rlimit-nofile <N>]
  crisol list [<path>...] [--group <name>]... [--all-groups] [--json]
  crisol closure <entrypoint>... [--json] [--config <path>]
  crisol closure --all [--json] [--config <path>]
  crisol clean [--all] [--config <path>]

  crisol --help | -h
  crisol --version | -V | version

Subcommands:
  run      Discover, compile, and run test entrypoints.
  list     Show what WOULD run (the plan) without compiling or running anything.
  closure  Read-only: show the recorded depgraph entry (group, flagHash,
           closure files, closureHash) for one or more planned entrypoints,
           or every discovered entrypoint with --all.  No compile, no run,
           no lock.
  clean    Prune orphan cache/bin dirs and stale depgraph entries.
           --all removes the entire state dir.  --config overrides the config file.

Options for 'run' and 'list':
  <path>...       Restrict discovery to these paths/globs (default: convention
                  globs from config — tests/unit/test_*.nim, etc.).
  --group <name>  Run only the named group(s); repeatable.  Mutually exclusive
                  with --all-groups (specifying both is a usage error).
  --all-groups    Include opt-in groups (gates still apply).

Additional options for 'run':
  --jobs N, -j N  Parallel job cap.  Default: max(1, cpu_count - 2).
  --timeout S, -t S
                  Per-entrypoint run timeout in seconds.  Default: 300.
  --fail-fast     Stop launching new entrypoints after the first failure.
  --dry-run       Print the plan (selection + per-entrypoint compile decisions)
                  and exit; compile and run NOTHING.
  --json          Emit machine-readable JSON to stdout instead of human output.
  --failed        Re-run only entrypoints that failed in the last run
                  (reads .crisol/lastrun.json; exit 3 if absent).
  --changed       Impact selection: run only entrypoints whose dependency
                  closure intersects the git diff.  Requires a git work tree
                  (exit 3 otherwise).  Combined with --failed, selects the
                  UNION of the two narrowed sets.
  --base <ref>    With --changed, diff the working tree against <ref> instead
                  of HEAD (includes uncommitted edits).  Ignored (with a
                  warning) when --changed is absent.
  --force-compile Force recompilation of all entrypoints even when fresh.
  --filter-tag T  Reporting-level filter: show ONLY test records tagged T.
                  Entrypoints still run in full; only the report is filtered.
                  Emits a warning to stderr when no records match the tag.
                  Exit code is unchanged by the filter.
  --order <mode>  History-based execution order: recent-fail (surface recently-
                  failing tests first for minimum time-to-first-failure),
                  duration (longest-running first for best parallelism),
                  or none (default: no reorder).
  --hermetic <L>  Hermeticity level for child sandboxes: none (no env scrub /
                  no rlimits / inherit parent env), isolated (default: env
                  allowlist + isolated tmpdir + config-declared rlimits), or
                  network (superset of isolated + net-ns isolation; currently
                  degrades — net-ns not wired — so such runs are not cached).
  --rlimit-nofile N
                  Override RLIMIT_NOFILE (max open fds) for hermetic sandbox
                  children.  Default: 1024 (or crisol.kdl's `rlimit-nofile`,
                  if set).  Raise this for fd-heavy consumer workloads (e.g.
                  one eventfd per in-flight async call) without patching
                  crisol.
  --measure-compile-reuse
                  Diagnostic: run compile slots through the measurement
                  worker and emit the `compile` block's segmented cc%/
                  r_time/r_size stats to the run report (no caching).

Additional options for 'list':
  --json          Emit the crisol/plan/v1 JSON document instead of human output.

Options for 'closure':
  <entrypoint>... Show the recorded depgraph entry for one or more planned
                  paths (repeatable).  Mutually exclusive with --all
                  (specifying both is a usage error); one of the two is
                  required.  A path matching no discovered entrypoint at all
                  is a configuration error (exit 3), same as `run`.  A path
                  whose only match was discovered but gated out prints an
                  empty report and exits 0, also same as `run`.
  --all           Show every discovered entrypoint, one crisol/closure/v1
                  document.  Discovery gates still apply: this is the same
                  set `crisol list --all-groups` would show — a gated-out
                  entrypoint is not listed (and --all with zero discovered
                  entrypoints is not an error; it prints an empty report).
  --json          Emit the crisol/closure/v1 JSON document instead of human
                  output.
  --config <path> Use this config file instead of walking up from the
                  current directory for crisol.kdl.
  Each entry's `closure` paths are project-root-relative (forward slashes)
  for in-root files, and absolute for files under a configured dep-root.

Exit codes:
  0   All selected entrypoints passed (or a pure listing succeeded).
  1   One or more entrypoints failed / compile-failed / timed-out / signaled.
  2   Crisol internal error (should not occur in normal operation).
  3   Environment / configuration error (bad args, no entrypoints found, etc.).
"""

# ---------------------------------------------------------------------------
# Color decision: pure helper + isatty wrapper
# ---------------------------------------------------------------------------

proc computeColorEnabled(): bool =
  ## Returns true iff stdout is a TTY AND NO_COLOR is unset.
  let tty = isatty(1.cint) != 0   # fd 1 = stdout
  shouldEnableColor(tty)

proc takeConfigFlag(args: seq[string]; ci: var int; dest: var string): bool =
  ## Parses `--config <path>` / `--config=<path>` at `args[ci]` — the caller
  ## has already confirmed `args[ci]` is one of those two forms (`== "--config"`
  ## or `.startsWith("--config=")`).  For the space-separated form, advances
  ## `ci` past the consumed value token (so the caller's enclosing `while`
  ## loop's `inc ci` lands past it, same as before this helper existed).
  ##
  ## Sets `dest` and returns true on success.  Returns false (leaving `dest`
  ## unchanged) when the value is missing (space-separated form with no next
  ## token) or empty (`--config=` with nothing after the `=`) — the caller
  ## then prints "crisol: --config requires a file path" and returns
  ## ExitEnvironment, exactly as the inlined duplicate blocks did.
  let a = args[ci]
  if a == "--config":
    inc ci
    if ci >= args.len:
      return false
    dest = args[ci]
    return true
  else:
    dest = a[9..^1]   # strip "--config="
    return dest != ""

# ---------------------------------------------------------------------------
# runMain — testable entry; returns the process exit code
# ---------------------------------------------------------------------------

proc runMain*(args: seq[string]; selfWorkerBinary: string = ""): int =
  ## Parse `args` (argv without the program name), execute the pipeline,
  ## and return the exit code.  Does NOT call quit().
  ##
  ## `selfWorkerBinary` becomes `RunOptions.workerBinary` (see below) and
  ## therefore the self-reexec target for RFC-0006's measureCompileReuse
  ## compile-slot worker.  It defaults to "" (no
  ## worker) rather than resolving `getAppFilename()` itself, because
  ## `getAppFilename()` returns whatever process is CURRENTLY RUNNING —
  ## sound only when that process is genuinely the crisol CLI binary (which
  ## dispatches InternalMeasureCompileToken,
  ## below).  `runMain` is also called IN-PROCESS by crisol's own test
  ## suite and by any library embedder that links against `crisol` as a
  ## module — for those callers `getAppFilename()` would point at the TEST
  ## or HOST binary, whose entrypoint does NOT dispatch either internal
  ## token, so a self-reexec would just re-run that whole program (unsound,
  ## up to an unbounded recursive fork). The real CLI binary's own
  ## `when isMainModule` entrypoint (bottom of this file) is the ONLY
  ## caller that passes `getAppFilename()` here — it alone can prove it IS
  ## that sound target. Every other caller gets the safe default: an empty
  ## workerBinary degrades spawnCompileStable to the monolithic compile
  ## path (see runner.nim / types.Config.workerBinary's own doc).

  if args.len == 0:
    stderr.write(usage())
    return ExitEnvironment

  let sub = args[0]

  if sub in ["-h", "--help"]:
    stdout.write(usage())
    return ExitOk

  if sub in ["--version", "-V", "version"]:
    stdout.write("crisol " & CrisolVersion & "\n")
    return ExitOk

  # RFC-0006 M-artifact-identity (pass (b1)): the internal measurement-worker
  # re-exec surface (`crisol --internal-measure-compile <plan.json>`).
  # Deliberately routed here, before subcommand validation, and NOT listed in
  # usage() — this is an internal re-exec token, not a user-facing
  # subcommand. See crisol/measureworker.nim for the worker pipeline.
  if sub == InternalMeasureCompileToken:
    if args.len < 2:
      stderr.write("crisol: " & InternalMeasureCompileToken &
                   " requires a <plan.json> path\n")
      return ExitEnvironment
    return runMeasureCompileWorker(args[1])

  if sub notin ["run", "list", "clean", "init", "closure"]:
    stderr.write("crisol: unknown subcommand '" & sub & "'\n\n")
    stderr.write(usage())
    return ExitEnvironment

  let isList  = sub == "list"
  let isClean = sub == "clean"

  # -------------------------------------------------------------------------
  # `clean` subcommand: orphan pruning (+ --all).
  # Handled early, before the shared run/list flag parser.
  # -------------------------------------------------------------------------

  if isClean:
    var doCleanAll    = false
    var cleanCfgPath  = ""
    let cleanArgs = args[1..^1]
    var ci = 0
    while ci < cleanArgs.len:
      let a = cleanArgs[ci]
      if a == "--all":
        doCleanAll = true
      elif a == "--config" or a.startsWith("--config="):
        if not takeConfigFlag(cleanArgs, ci, cleanCfgPath):
          stderr.write("crisol: --config requires a file path\n")
          return ExitEnvironment
      else:
        stderr.write("crisol: unknown flag for clean: '" & a & "'\n")
        return ExitEnvironment
      inc ci

    let (cfg, _) = loadConfig(configPath = cleanCfgPath)
    let stateDir = stateDirOf(cfg)

    if doCleanAll:
      # --all: remove the whole state dir — no lock needed.
      try:
        cleanAll(cfg)
      except Exception as e:
        stderr.write("crisol: clean --all failed: " & e.msg & "\n")
        return ExitInternal
      return ExitOk

    # Acquire the lock before mutating shared state.
    var lockHandle: LockHandle
    try:
      lockHandle = acquireLock(stateDir)
    except CrisolError as e:
      stderr.write("crisol: " & e.msg & "\n")
      return ExitEnvironment

    defer: releaseLock(lockHandle)

    try:
      # RFC-0006 nimcache-persistence GC: real toolchain probe so cache/
      # pruning correctly orphans dirs left over from an old cc/nim
      # fingerprint (see cleanOrphans' doc). nimVersion uses the RUNTIME
      # nim fingerprint (nimprobe.cachedNimFingerprint), not crisolNimVersion —
      # same soundness rule as api.nim's cache-identity feeds.
      let r = cleanOrphans(cfg, nimVersion = cachedNimFingerprint(), ccVersion = cachedCcVersion())
      stdout.write("crisol clean: pruned " & $r.cacheDeleted &
                   " cache dir(s), " & $r.binDeleted &
                   " bin dir(s), " & $r.graphEntriesDropped &
                   " depgraph entry(ies); evicted " & $r.cacheEvicted &
                   " result-cache entry(ies); compacted " &
                   $r.shardsRemoved & " ledger shard(s) (" &
                   $r.ledgerRowsKept & " row(s) kept); compacted " &
                   $r.artifactReport.shardsRemoved & " artifact shard(s) (" &
                   $r.artifactReport.rowsKept & " row(s) kept); compacted " &
                   $r.compileCostReport.shardsRemoved & " compile-cost shard(s) (" &
                   $r.compileCostReport.rowsKept & " row(s) kept)\n")
    except CrisolError as e:
      stderr.write("crisol: clean error: " & e.msg & "\n")
      return ExitEnvironment
    except Exception as e:
      stderr.write("crisol: clean unexpected error: " & e.msg & "\n")
      return ExitInternal

    return ExitOk

  # -------------------------------------------------------------------------
  # `init` subcommand: write canonical starter crisol.kdl.
  # -------------------------------------------------------------------------

  if sub == "init":
    var targetPath = "crisol.kdl"   # default: crisol.kdl in cwd
    var forceInit  = false
    let initArgs = args[1..^1]
    var ii = 0
    while ii < initArgs.len:
      let a = initArgs[ii]
      if a == "--force":
        forceInit = true
      elif a.startsWith("-"):
        stderr.write("crisol: unknown flag for init: '" & a & "'\n")
        return ExitEnvironment
      else:
        targetPath = a
      inc ii

    let absTarget = if isAbsolute(targetPath): targetPath
                    else: getCurrentDir() / targetPath

    # Single atomic open() — no TOCTOU, no symlink follow-through.
    #
    # O_NOFOLLOW: refuse to follow a symlink at the final path component on
    #             every branch, including --force (no write-through).
    # O_EXCL:     atomically refuse if ANYTHING already exists (without --force).
    # O_TRUNC:    truncate an existing regular file when --force is set.
    # Mode 0o644: owner rw, group r, other r.
    let baseFlags = O_CREAT or O_WRONLY or O_NOFOLLOW_FLAG
    let openFlags = if forceInit: baseFlags or O_TRUNC
                    else:         baseFlags or O_EXCL
    let fd = posix.open(absTarget.cstring, openFlags, 0o644.Mode)

    if fd < 0:
      let err = errno
      if err == EEXIST or err == ELOOP:
        # EEXIST: file exists and --force not given (O_EXCL triggered).
        # ELOOP:  O_NOFOLLOW caught a symlink (both with and without --force).
        if err == ELOOP or (not forceInit):
          stderr.write("crisol: init: '" & absTarget & "' already exists; " &
                       "use --force to overwrite\n")
        else:
          stderr.write("crisol: init: cannot write '" & absTarget & "': " &
                       $strerror(err) & "\n")
      else:
        stderr.write("crisol: init: cannot write '" & absTarget & "': " &
                     $strerror(err) & "\n")
      return ExitEnvironment

    # Write InitTemplate in a short-write-safe loop, then close on every path.
    let content = InitTemplate
    let contentLen = content.len
    var written = 0
    var writeOk = true
    while written < contentLen:
      let n = posix.write(fd, cast[pointer](unsafeAddr content[written]),
                          contentLen - written)
      if n < 0:
        let err = errno
        stderr.write("crisol: init: cannot write '" & absTarget & "': " &
                     $strerror(err) & "\n")
        writeOk = false
        break
      written += n.int
    discard posix.close(fd)

    if not writeOk:
      return ExitEnvironment

    stdout.write("crisol: init: wrote " & absTarget & "\n")
    return ExitOk

  # -------------------------------------------------------------------------
  # `closure` subcommand: issue #9 slice A — read-only depgraph projection.
  # Handled early, before the shared run/list flag parser: closure has its
  # own minimal flag set (positional <entrypoint> XOR --all, plus --json)
  # and shares NONE of run/list's tuning flags.
  # -------------------------------------------------------------------------

  if sub == "closure":
    var closurePaths: seq[string]
    var closureAll   = false
    var closureJson  = false
    var closureCfgPath = ""   # --config <path> / --config=<path>
    let closureArgs = args[1..^1]
    var ci = 0
    while ci < closureArgs.len:
      let a = closureArgs[ci]
      if a == "--all":
        closureAll = true
      elif a == "--json":
        closureJson = true
      elif a == "--config" or a.startsWith("--config="):
        if not takeConfigFlag(closureArgs, ci, closureCfgPath):
          stderr.write("crisol: --config requires a file path\n")
          return ExitEnvironment
      elif a.startsWith("-"):
        stderr.write("crisol: unknown flag for closure: '" & a & "'\n")
        return ExitEnvironment
      else:
        closurePaths.add a
      inc ci

    if closureAll and closurePaths.len > 0:
      stderr.write("crisol: 'closure' accepts either <entrypoint> or --all, " &
                   "not both\n\n")
      stderr.write(usage())
      return ExitEnvironment

    if not closureAll and closurePaths.len == 0:
      stderr.write("crisol: closure requires <entrypoint> or --all\n\n")
      stderr.write(usage())
      return ExitEnvironment

    let closureSelection =
      if closureAll: allGroups()
      else: filesSelection(closurePaths)

    var cr: ClosureReport
    try:
      cr = closureReport(RunOptions(selection: closureSelection,
                                    configPath: closureCfgPath))
    except CrisolError as e:
      case e.kind
      of cekEnvironment:
        stderr.write("crisol: environment error: " & e.msg & "\n")
        return ExitEnvironment
      of cekConfig:
        stderr.write("crisol: config error: " & e.msg & "\n")
        return ExitEnvironment
      of cekInternal:
        stderr.write("crisol: internal error: " & e.msg & "\n")
        return ExitInternal

    for w in cr.warnings:
      stderr.write("warning: " & w.message & "\n")

    # Issue #3 / RFC-0001:409: warn about ad-hoc / ambiguous gskFiles
    # paths, same as run/list.  closure has no --group flag, so withinGroups
    # is always empty here.
    for line in pathFlagsWarnings(cr.adHocPaths, cr.ambiguousPaths, @[]):
      stderr.write("crisol: " & line & "\n")

    # A positional <entrypoint>... selection that matched no discovered
    # entrypoint at all is a configuration error, same as `run` (exit 3).
    # A selection whose only match(es) were discovered but GATED OUT is
    # NOT that case — it lands in cr.gatedOut, not cr.entries — and `run`
    # exits 0 for the identical selection (zrkAllGated); `closure` matches
    # that contract: print the (empty-entries) report and exit 0.  `--all`
    # with zero discovered entrypoints is likewise NOT an error (an empty
    # report is a legitimate answer to "what's discovered").
    if not closureAll and cr.entries.len == 0 and cr.gatedOut.len == 0:
      stderr.write("crisol: no entrypoints matched — check config/globs\n")
      return ExitEnvironment

    if closureJson:
      stdout.write(closureToJsonString(cr))
      stdout.write("\n")
    else:
      stdout.write(renderClosure(cr))
    return ExitOk

  # -------------------------------------------------------------------------
  # Parse flags (run + list share most; run adds jobs/timeout/fail-fast/dry-run)
  # -------------------------------------------------------------------------

  var
    paths:        seq[string]
    groupNames:   seq[string]   # collected from --group (repeatable)
    allGroups:    bool = false  # set by --all-groups
    configPath:   string = ""   # C1: --config <path> override
    jobs:         int  = 0
    timeout:      int  = 0
    failFast:     bool = false
    jsonMode:     bool = false
    dryRun:       bool = false
    useFailed:    bool = false
    useChanged:   bool = false  # D5: impact selection via git diff
    baseRef:      string = ""   # D5: --base <ref>; "" means diff vs HEAD
    forceCompile: bool = false
    noCache:      bool = false  # A9: --no-cache: do NOT read/write the result cache
    filterTag:    string = ""   # C3: reporting-level record filter
    retries:      int  = -1     # B1: --retries N; -1 = not specified (use config)
    failOnFlaky:  bool = false  # B1: --fail-on-flaky: flaky-passes → exit 1
    junitPath:    string = ""   # C1: --junit <path> JUnit XML report output path
    shardK:       int  = 0      # C2: shard index (1-indexed); 0 = no sharding
    shardN:       int  = 1      # C2: total shard count; only used when shardK > 0
    orderMode:    OrderMode = omNone  # C4: history-based prioritization
    perfCheck:    bool = false  # C6: --perf-check: force perf-regression detection ON
    hermeticLevel: HermeticLevel = hlIsolated  # RFC-0004: --hermetic none|isolated|network
    measureCompileReuse: bool = false  # RFC-0006: --measure-compile-reuse: gate the
                                        # measurement worker into the compile slot
    rlimitNofile: int = 0        # Fix 1: --rlimit-nofile N; 0 = not specified (use config/built-in)

  let runArgs = args[1..^1]
  var i = 0
  while i < runArgs.len:
    let a = runArgs[i]
    if a.startsWith("--"):
      let flagBody = a[2..^1]
      var key = flagBody
      var valInline = ""
      var hasInline = false
      let eq = flagBody.find('=')
      if eq >= 0:
        key = flagBody[0..<eq]
        valInline = flagBody[eq+1..^1]
        hasInline = true

      proc nextVal(name: string): string =
        if hasInline: return valInline
        if i + 1 < runArgs.len and not runArgs[i+1].startsWith("-"):
          inc i
          return runArgs[i]
        stderr.write("crisol: --" & name & " requires a value\n")
        return ""

      # Flags valid only for `run`.
      if key in ["jobs", "timeout", "fail-fast", "dry-run", "failed", "changed",
                 "base", "force-compile", "no-cache", "filter-tag",
                 "retries", "fail-on-flaky", "junit", "shard", "order",
                 "perf-check", "hermetic", "measure-compile-reuse",
                 "rlimit-nofile"] and isList:
        stderr.write("crisol: '--" & key & "' is not valid for 'list'\n\n")
        stderr.write(usage())
        return ExitEnvironment

      case key
      of "config":
        let raw = nextVal("config")
        if raw == "":
          stderr.write("crisol: --config requires a file path\n")
          return ExitEnvironment
        configPath = raw
      of "group":
        let raw = nextVal("group")
        if raw == "":
          stderr.write("crisol: --group requires a group name\n")
          return ExitEnvironment
        groupNames.add raw
      of "all-groups":
        allGroups = true
      of "jobs":
        let raw = nextVal("jobs")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          jobs = parseInt(raw)
          if jobs < 1:
            stderr.write("crisol: --jobs must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --jobs: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "timeout":
        let raw = nextVal("timeout")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          timeout = parseInt(raw)
          if timeout < 1:
            stderr.write("crisol: --timeout must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --timeout: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "fail-fast":
        failFast = true
      of "dry-run":
        dryRun = true
      of "json":
        jsonMode = true
      of "failed":
        useFailed = true
      of "changed":
        useChanged = true
      of "base":
        let raw = nextVal("base")
        if raw == "":
          stderr.write("crisol: --base requires a git ref\n")
          return ExitEnvironment
        baseRef = raw
      of "force-compile":
        forceCompile = true
      of "no-cache":
        noCache = true
      of "retries":
        let raw = nextVal("retries")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          retries = parseInt(raw)
          if retries < 0:
            stderr.write("crisol: --retries must be >= 0\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --retries: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "fail-on-flaky":
        failOnFlaky = true
      of "junit":
        let raw = nextVal("junit")
        if raw == "":
          stderr.write("crisol: --junit requires a file path\n")
          return ExitEnvironment
        junitPath = raw
      of "filter-tag":
        let raw = nextVal("filter-tag")
        if raw == "":
          stderr.write("crisol: --filter-tag requires a tag name\n")
          return ExitEnvironment
        filterTag = raw
      of "shard":
        let raw = nextVal("shard")
        if raw == "":
          stderr.write("crisol: --shard requires a k/n value (e.g. --shard 1/3)\n")
          return ExitEnvironment
        try:
          let parsed = parseShardSpec(raw)
          shardK = parsed.k
          shardN = parsed.n
        except ValueError as e:
          stderr.write("crisol: " & e.msg & "\n")
          return ExitEnvironment
      of "order":
        let raw = nextVal("order")
        if raw == "":
          stderr.write("crisol: --order requires a mode (recent-fail, duration, none)\n")
          return ExitEnvironment
        try:
          orderMode = parseOrderMode(raw)
        except ValueError as e:
          stderr.write("crisol: " & e.msg & "\n")
          return ExitEnvironment
      of "perf-check":
        perfCheck = true
      of "measure-compile-reuse":
        measureCompileReuse = true
      of "hermetic":
        let raw = nextVal("hermetic")
        if raw == "":
          stderr.write("crisol: --hermetic requires a level (none, isolated, network)\n")
          return ExitEnvironment
        case raw
        of "none":     hermeticLevel = hlNone
        of "isolated": hermeticLevel = hlIsolated
        of "network":  hermeticLevel = hlNetwork
        else:
          stderr.write("crisol: --hermetic: invalid level '" & raw &
                       "' (expected none, isolated, or network)\n")
          return ExitEnvironment
      of "rlimit-nofile":
        let raw = nextVal("rlimit-nofile")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          rlimitNofile = parseInt(raw)
          if rlimitNofile < 1:
            stderr.write("crisol: --rlimit-nofile must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --rlimit-nofile: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      else:
        stderr.write("crisol: unknown flag '--" & key & "'\n\n")
        stderr.write(usage())
        return ExitEnvironment
    elif a.startsWith("-") and a.len > 1:
      let key = a[1..^1]
      proc nextVal2(name: string): string =
        if i + 1 < runArgs.len and not runArgs[i+1].startsWith("-"):
          inc i
          return runArgs[i]
        stderr.write("crisol: -" & name & " requires a value\n")
        return ""
      if key in ["j", "t"] and isList:
        stderr.write("crisol: '-" & key & "' is not valid for 'list'\n\n")
        stderr.write(usage())
        return ExitEnvironment
      case key
      of "j":
        let raw = nextVal2("j")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          jobs = parseInt(raw)
          if jobs < 1:
            stderr.write("crisol: --jobs must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --jobs: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      of "t":
        let raw = nextVal2("t")
        if raw == "":
          stderr.write(usage()); return ExitEnvironment
        try:
          timeout = parseInt(raw)
          if timeout < 1:
            stderr.write("crisol: --timeout must be >= 1\n"); return ExitEnvironment
        except ValueError:
          stderr.write("crisol: --timeout: invalid integer '" & raw & "'\n")
          return ExitEnvironment
      else:
        stderr.write("crisol: unknown flag '-" & key & "'\n\n")
        stderr.write(usage())
        return ExitEnvironment
    else:
      paths.add a
    inc i

  # -------------------------------------------------------------------------
  # Build config and apply CLI overrides
  # -------------------------------------------------------------------------

  # --group and --all-groups are mutually exclusive: they are semantically
  # contradictory (named subset vs. full set), so we error rather than silently
  # picking a winner.
  if groupNames.len > 0 and allGroups:
    stderr.write("crisol: --group and --all-groups are mutually exclusive\n\n")
    stderr.write(usage())
    return ExitEnvironment

  let colorEnabled = computeColorEnabled()

  # Build GroupSelection from parsed flags.
  #
  # Issue #3 / RFC-0001:409: paths and --group are NOT mutually exclusive — a
  # path narrows WHICH files run, --group narrows WHICH configured groups are
  # candidate owners for those paths.  withinGroups carries --group through so
  # discover() still validates/attributes against the named group(s) instead
  # of silently dropping --group whenever a path is also given.
  var selection: GroupSelection
  if paths.len > 0:
    selection = GroupSelection(kind: gskFiles, paths: paths, withinGroups: groupNames)
  elif allGroups:
    selection = GroupSelection(kind: gskAll)
  elif groupNames.len > 0:
    selection = GroupSelection(kind: gskNamed, names: groupNames)
  else:
    selection = GroupSelection(kind: gskDefault)

  # --base without --changed is a CLI error (exit 3): --base is meaningless
  # without narrowing and silently ignoring it would always be a mistake.
  if baseRef.len > 0 and not useChanged:
    stderr.write("crisol: error: --base requires --changed " &
                 "(a base ref without impact selection has no effect)\n")
    return ExitEnvironment

  # Build narrowing.
  var narrowing: RunNarrowing
  if useFailed and useChanged:
    narrowing = failedOrChanged(baseRef)
  elif useChanged:
    narrowing = changedOnly(baseRef)
  elif useFailed:
    narrowing = failedOnly()
  else:
    narrowing = noNarrowing()

  let opts = RunOptions(
    configPath:          configPath,
    selection:           selection,
    narrowing:           narrowing,
    forceCompile:        forceCompile,
    failFast:            failFast,
    noCache:             noCache,
    jobs:                jobs,
    timeoutSecs:         timeout,
    showProgress:        not jsonMode,
    progressIntervalMs:  30_000,
    manageLock:          true,
    installSignals:      true,
    persist:             true,
    retries:             retries,       # B1: -1 = use config; >= 0 = override
    failOnFlaky:         failOnFlaky,   # B1: flaky-pass → exit 1
    shardK:              shardK,        # C2: shard index (0 = no sharding)
    shardN:              shardN,        # C2: total shard count
    order:               orderMode,     # C4: history-based prioritization
    perfCheckForce:      perfCheck,     # C6: --perf-check: force detection ON
    hermeticLevel:       hermeticLevel, # RFC-0004: --hermetic level control
    rlimitNofile:        if rlimitNofile > 0: some(int64(rlimitNofile)) else: none(int64),
                                         # Fix 1: --rlimit-nofile override
    measureCompileReuse: measureCompileReuse,  # RFC-0006: gate measurement worker into compile slot
    workerBinary:        selfWorkerBinary,  # "" unless the real CLI entrypoint (below) passed
                                             # its own getAppFilename() — see runMain's doc above
                                             # for why this must never be resolved in here.
  )

  # -------------------------------------------------------------------------
  # `list` and `run --dry-run`: pure plan phase; no lock, no subprocess.
  # -------------------------------------------------------------------------

  if isList or dryRun:
    var pr: PlanReport
    try:
      pr = planTests(opts)
    except CrisolError as e:
      case e.kind
      of cekEnvironment:
        stderr.write("crisol: environment error: " & e.msg & "\n")
        return ExitEnvironment
      of cekConfig:
        stderr.write("crisol: config error: " & e.msg & "\n")
        return ExitEnvironment
      of cekInternal:
        stderr.write("crisol: internal error: " & e.msg & "\n")
        return ExitInternal

    # Emit config warnings.
    for w in pr.warnings:
      stderr.write("warning: " & w.message & "\n")

    # Issue #3 / RFC-0001:409: warn about ad-hoc / ambiguous gskFiles paths.
    for line in pathFlagsWarnings(pr.adHocPaths, pr.ambiguousPaths, groupNames):
      stderr.write("crisol: " & line & "\n")

    if jsonMode:
      stdout.write(planToJsonString(pr))
      stdout.write("\n")
    else:
      let ropts = RenderOpts(color: colorEnabled, slowestN: 5)
      stdout.write(renderPlan(pr, ropts))
    return ExitOk

  # -------------------------------------------------------------------------
  # `run`: full execution via runTests.
  # -------------------------------------------------------------------------

  let rr = runTests(opts)

  # Emit config warnings to stderr.
  for w in rr.plan.warnings:
    stderr.write("warning: " & w.message & "\n")

  # Issue #3 / RFC-0001:409: warn about ad-hoc / ambiguous gskFiles paths.
  for line in pathFlagsWarnings(rr.plan.adHocPaths, rr.plan.ambiguousPaths, groupNames):
    stderr.write("crisol: " & line & "\n")

  if rr.status == rsStructural:
    stderr.write("crisol: " & rr.error & "\n")
    return rr.exitCode

  if rr.status == rsInterrupted:
    return rr.exitCode

  # Zero-runnable exit-0 branches: rsOk with zero results.
  if rr.results.len == 0 and rr.status == rsOk:
    case rr.zeroRunnableReason
    of zrkChangedClean:
      stdout.write("crisol: nothing affected by the changes — nothing to run\n")
      return ExitOk
    of zrkFailedNone:
      stdout.write("crisol: no previously-failed entrypoints to re-run\n")
      return ExitOk
    of zrkAllGated:
      for line in gateSkipMessages(rr.plan.gatedOut):
        stdout.write(line & "\n")
      stdout.write("crisol: all groups gated out — nothing to run\n")
      return ExitOk
    of zrkNone:
      discard  # fall through to normal reporting

  # Fail-fast message.
  let totalPlanned = rr.plan.entrypoints.len
  if opts.failFast and rr.results.len < totalPlanned:
    let skipped = totalPlanned - rr.results.len
    stderr.write("crisol: fail-fast — stopped after first failure; " &
                 $skipped & " entrypoint(s) not started\n")

  # C3: zero-match warning.
  if filterTag.len > 0 and hasZeroTagMatches(rr.results, filterTag):
    stderr.write("crisol: warning: no test records matched tag \"" & filterTag & "\"\n")

  if jsonMode:
    stdout.write(toJsonString(rr.results, rr.summary, filterTag, rr.plan.warnings, rr.memThrottledSlots))
    stdout.write("\n")
  else:
    let ropts = RenderOpts(color: colorEnabled, slowestN: 5,
                           filterTag: if filterTag.len > 0: some(filterTag)
                                      else: none(string))
    stdout.write(render(rr.results, rr.summary, ropts))
    # Gate-skip messages after results.
    if rr.plan.gatedOut.len > 0:
      for line in gateSkipMessages(rr.plan.gatedOut):
        stdout.write(line & "\n")

  # C1: --junit <path> — write JUnit XML report as an additional output sink.
  # Composes with normal stdout reporting (--json or human render still runs).
  if junitPath.len > 0:
    let xmlStr = toJunitXml(rr.results, rr.summary)
    try:
      writeFile(junitPath, xmlStr)
    except IOError as e:
      stderr.write("crisol: warning: could not write junit report to '" &
                   junitPath & "': " & e.msg & "\n")
    except OSError as e:
      stderr.write("crisol: warning: could not write junit report to '" &
                   junitPath & "': " & e.msg & "\n")

  return rr.exitCode

# ---------------------------------------------------------------------------
# Binary entry point
# ---------------------------------------------------------------------------

when isMainModule:
  # This IS the real crisol CLI binary: it dispatches
  # InternalMeasureCompileToken (above, before
  # subcommand validation), so its own getAppFilename() is a sound
  # self-reexec target for RFC-0006's measurement compile-slot worker. This
  # is the ONLY call site allowed to pass a non-empty selfWorkerBinary — see
  # runMain's doc.
  let code = runMain(commandLineParams(), selfWorkerBinary = getAppFilename())
  quit(code)
