## test_artifactid.nim — unit tests for artifactid.nim (RFC-0006
## M-artifact-identity, pass (a): pure identity + ratio core).
##
## All seams injected: NO real `cc`/`nim` invocation anywhere in this file
## (the one real `cc -M` check lives in
## tests/integration/test_artifactid_real.nim). The golden-fixture
## re-validation (production `normalize()`/`reuseRatios()` reproducing the
## committed golden's closed-form r_size/r_time) lives in
## tests/unit/test_golden_reuse.nim, which this slice rewrote to call this
## module directly instead of its old fixture-local `stripHeader` scaffold.
##
## Run with:
##   ./dev run nim r --hints:off --warnings:off --path:src \
##         tests/unit/test_artifactid.nim

import std/[options, sequtils, strutils, tables, unittest]
import crisol/artifactid   # re-exports toolrun.RunProc/realRun
import crisol/paths         # CR3/CR10: TrackedRoots/classify's ReportedPath overload

# ===========================================================================
# Behavior 1 — normalize(): 4-line header strip + known-string erasure
# ===========================================================================

suite "normalize — Nim-generated header strip + known cacheDir/binDir erasure":

  test "strips the fixed 4-line Nim-generated header when the marker is present":
    let content = "/* Generated by Nim Compiler v2.2.10 */\n" &
                  "/* Compiled for: Linux, amd64, gcc */\n" &
                  "/* Command for C compiler:\n" &
                  "   gcc -c /nimcache_slot7/@mfoo.nim.c */\n" &
                  "#define NIM_INTBITS 64\n" &
                  "N_LIB_PRIVATE void foo(void) {}\n"
    let normalized = normalize(content, @[])
    check normalized == "#define NIM_INTBITS 64\nN_LIB_PRIVATE void foo(void) {}\n"

  test "does NOT strip a vendor .c file's own leading comment (no Nim marker present)":
    let vendor = "/* fixture.c — companion C source, not Nim-generated */\n" &
                 "#include \"fixture.h\"\n" &
                 "int crisol_fixture_double(int x) { return x * 2; }\n"
    check normalize(vendor, @[]) == vendor

  test "two real golden-shaped .c samples differing ONLY in per-slot header become byte-identical":
    proc makeUnit(cacheDir: string): string =
      "/* Generated by Nim Compiler v2.2.10 */\n" &
      "/* Compiled for: Linux, amd64, gcc */\n" &
      "/* Command for C compiler:\n" &
      "   gcc -c -w -I/opt/nim/2.2.10/lib -o " & cacheDir & "/@pfoo.nim.c.o " &
        cacheDir & "/@pfoo.nim.c */\n" &
      "#define NIM_INTBITS 64\n" &
      "N_LIB_PRIVATE void foo(void) {}\n"
    let a = makeUnit("/workspace/generated/ep_a")
    let b = makeUnit("/workspace/generated/ep_b")
    check a != b   # sanity: the strip is doing real work, not a no-op
    check normalize(a, @["/workspace/generated/ep_a"]) ==
          normalize(b, @["/workspace/generated/ep_b"])

  test "erases known cacheDir/binDir strings from a ccCmd, preserving real flag deltas":
    let ccCmd = "gcc -c -w -I/opt/nim/2.2.10/lib -I/proj/include -DFOO=1 " &
                "-o /proj/generated/ep_a_3/@pfoo.nim.c.o /proj/generated/ep_a_3/@pfoo.nim.c"
    let normalized = normalize(ccCmd, @["/proj/generated/ep_a_3"])
    check "/proj/generated/ep_a_3" notin normalized
    check "-I/opt/nim/2.2.10/lib" in normalized     # real flag, preserved
    check "-I/proj/include" in normalized           # real project -I, preserved
    check "-DFOO=1" in normalized                   # real flag, preserved

  test "erasing a known string that does not occur is a harmless no-op":
    let content = "plain content, no matches here\n"
    check normalize(content, @["/never/present"]) == content

  test "R14-T7: a real project token that is a SUPERSTRING of a known erasure string is NOT corrupted":
    ## `normalize()`'s known-string erasure is deliberately exact-substring,
    ## not regex — but a blind substring replace still has a boundary bug: a
    ## known cacheDir "/proj/gen/ep_a_3" is also a PREFIX of a real, distinct
    ## project token "-I/proj/gen/ep_a_3_vendor". A blind `.replace` would
    ## strip the shared prefix and leave a mangled "-I_vendor" remainder.
    ## normalize() must erase ONLY exact/prefix-bounded occurrences of the
    ## known string (i.e. not followed by an identifier character), leaving
    ## the superstring token completely untouched.
    let ccCmd = "gcc -c -I/proj/gen/ep_a_3_vendor -o /proj/gen/ep_a_3/@pfoo.nim.c.o " &
                "/proj/gen/ep_a_3/@pfoo.nim.c"
    let normalized = normalize(ccCmd, @["/proj/gen/ep_a_3"])
    check "-I/proj/gen/ep_a_3_vendor" in normalized      # superstring token untouched
    check "/proj/gen/ep_a_3/@pfoo.nim.c.o" notin normalized  # exact known-dir occurrence still erased
    check "/proj/gen/ep_a_3/@pfoo.nim.c" notin normalized

# ===========================================================================
# Behavior 2 — normalize(): @response-file content inlining
# ===========================================================================

suite "normalize — @response-file content inlining":

  proc syntheticReader(mapping: Table[string, string]): FileReaderProc =
    result = proc(path: string): tuple[content: string; ok: bool] =
      if mapping.hasKey(path):
        (content: mapping[path], ok: true)
      else:
        (content: "", ok: false)

  test "a bare ccCmd with no @token is untouched":
    let ccCmd = "gcc -c -w -I/inc -o out.o in.c"
    let reader = syntheticReader(initTable[string, string]())
    check normalize(ccCmd, @[], reader) == ccCmd

  test "an @response-file token is replaced by a hash of its REFERENCED content":
    let ccCmd = "gcc -c @/tmp/args.rsp -o out.o in.c"
    let reader = syntheticReader({"/tmp/args.rsp": "-DFOO=1 -DBAR=2"}.toTable)
    let normalized = normalize(ccCmd, @[], reader)
    check "@/tmp/args.rsp" notin normalized   # literal path token is gone
    check "-o out.o in.c" in normalized       # everything else preserved verbatim

  test "identical response-file CONTENT (even at different paths) yields the SAME inlined digest":
    let cmdA = "gcc @/tmp/a.rsp -o out.o in.c"
    let cmdB = "gcc @/tmp/b.rsp -o out.o in.c"
    let reader = syntheticReader({"/tmp/a.rsp": "-DFOO=1", "/tmp/b.rsp": "-DFOO=1"}.toTable)
    check normalize(cmdA, @[], reader) == normalize(cmdB, @[], reader)

  test "a .rsp-only CONTENT change changes the normalized result even though the ccCmd string (sans content) is otherwise identical":
    let ccCmd = "gcc @/tmp/args.rsp -o out.o in.c"
    let readerV1 = syntheticReader({"/tmp/args.rsp": "-DFOO=1"}.toTable)
    let readerV2 = syntheticReader({"/tmp/args.rsp": "-DFOO=2"}.toTable)
    check normalize(ccCmd, @[], readerV1) != normalize(ccCmd, @[], readerV2)

  test "an unreadable response file degrades to a distinct sentinel-derived digest rather than raising":
    let ccCmd = "gcc @/tmp/missing.rsp -o out.o in.c"
    let reader = syntheticReader(initTable[string, string]())
    let normalized = normalize(ccCmd, @[], reader)
    check "@/tmp/missing.rsp" notin normalized
    check normalized.len > 0

# ===========================================================================
# Behavior 3 — ccIncludeClosure(): synthetic cc -M parsing + content hash
# ===========================================================================

suite "ccIncludeClosure — synthetic cc -M Make-output parsing + header content hash":

  proc syntheticReader(mapping: Table[string, string]): FileReaderProc =
    result = proc(path: string): tuple[content: string; ok: bool] =
      if mapping.hasKey(path):
        (content: mapping[path], ok: true)
      else:
        (content: "", ok: false)

  test "review Finding 1: deriveDepInvocation REPLICATES the real command verbatim, dropping only -c and -o <obj>":
    ## Previously an ALLOW-LIST (kept only -I/-D/-std, silently dropped
    ## everything else, including -w and -fmax-errors=3 here). Now a
    ## DENYLIST of exactly the two things a -M run must not carry: the
    ## compile-action flag and the output flag. Every other flag —
    ## including ones this probe doesn't specifically know about — must
    ## survive verbatim (see the two new tests below for -isystem/-include,
    ## the exact class of flag the allow-list used to silently drop).
    let ccCmd = "gcc -c -w -fmax-errors=3 -I/inc -I/nim/lib -DFOO=1 -std=c99 " &
                "-o /cache/@pfoo.nim.c.o /cache/@pfoo.nim.c"
    let inv = deriveDepInvocation(ccCmd)
    check inv.ok
    check inv.cmd == "gcc"
    check inv.sourceFile == "/cache/@pfoo.nim.c"
    check inv.args == @["-M", "-w", "-fmax-errors=3", "-I/inc", "-I/nim/lib",
                        "-DFOO=1", "-std=c99", "/cache/@pfoo.nim.c"]

  test "review Finding 1: -isystem is RETAINED (previously silently dropped by the allow-list — wrong-hit class)":
    ## -isystem changes where the compiler looks for headers exactly like -I
    ## does, just with system-header semantics; a project passing it via
    ## --passC is realistic. The pre-fix allow-list dropped it (it starts
    ## with neither -I, -D, nor -std), so the cc -M probe searched a
    ## DIFFERENT set of directories than the real compile — a header
    ## reachable only via -isystem could change in place without changing
    ## includeClosureContentHash, an undetected wrong-hit.
    let ccCmd = "gcc -c -w -isystem /vendor/inc -I/proj/inc -o /cache/mod.c.o /cache/mod.c"
    let inv = deriveDepInvocation(ccCmd)
    check inv.ok
    check "-isystem" in inv.args
    check "/vendor/inc" in inv.args
    check inv.args == @["-M", "-w", "-isystem", "/vendor/inc", "-I/proj/inc", "/cache/mod.c"]

  test "review Finding 1: -include is RETAINED (previously silently dropped by the allow-list — wrong-hit class)":
    ## -include force-includes a header before the translation unit even
    ## starts — every bit as header-resolution-relevant as -I. Same
    ## wrong-hit exposure as -isystem above under the pre-fix allow-list.
    let ccCmd = "gcc -c -include /proj/config.h -I/proj/inc -o /cache/mod.c.o /cache/mod.c"
    let inv = deriveDepInvocation(ccCmd)
    check inv.ok
    check "-include" in inv.args
    check "/proj/config.h" in inv.args
    check inv.args == @["-M", "-include", "/proj/config.h", "-I/proj/inc", "/cache/mod.c"]

  test "review Finding 1 regression: -c and space-separated -o <obj> are removed, -M added, source preserved, other flags verbatim":
    let ccCmd = "gcc -c -w -I/inc -o /cache/mod.c.o /cache/mod.c"
    let inv = deriveDepInvocation(ccCmd)
    check inv.ok
    check "-c" notin inv.args
    check "-o" notin inv.args
    check "/cache/mod.c.o" notin inv.args   # the -o argument itself is gone too
    check inv.args == @["-M", "-w", "-I/inc", "/cache/mod.c"]

  test "review Finding 1 regression: the fused -o<obj> form is dropped as a single token, other flags verbatim":
    let ccCmd = "gcc -c -w -I/inc -o/cache/mod.c.o /cache/mod.c"
    let inv = deriveDepInvocation(ccCmd)
    check inv.ok
    for a in inv.args:
      check not (a.startsWith("-o") and a.len > 2)   # no fused -o<obj> survives
    check inv.args == @["-M", "-w", "-I/inc", "/cache/mod.c"]

  test "R4: a ccCmd too short to derive a cc -M invocation degrades to ok=false, never raises":
    ## Previously `doAssert toks.len >= 2` — an AssertionDefect, a `Defect`
    ## NOT caught by a worker's `except CatchableError` escape hatch. A
    ## malformed/degenerate manifest entry must degrade gracefully like
    ## every other per-unit oddity in this module.
    let inv = deriveDepInvocation("gcc")   # single token — no source file
    check not inv.ok
    check inv.cmd == ""
    check inv.args.len == 0
    check inv.sourceFile == ""

  test "R1b: a shell-quoted -I path containing a space is tokenized correctly (shell-aware, not naive splitWhitespace)":
    ## Realistic under WSL2 / a mounted toolchain with a space in its path.
    ## Nim's own cc-command construction shell-quotes such an argument
    ## (`quoteShellPosix`) before it ever reaches the shell that actually
    ## runs the compile — so deriving the cc -M invocation must tokenize the
    ## SAME way, or the -I path is corrupted into two bogus tokens and the
    ## resulting closure probe silently omits headers reachable only via
    ## that -I.
    let ccCmd = "gcc -c -w '-I/opt/my toolchain/include' -o /cache/mod.c.o /cache/mod.c"
    let inv = deriveDepInvocation(ccCmd)
    check inv.ok
    check inv.cmd == "gcc"
    check inv.sourceFile == "/cache/mod.c"
    check "-I/opt/my toolchain/include" in inv.args
    check inv.args == @["-M", "-w", "-I/opt/my toolchain/include", "/cache/mod.c"]

  test "R1b: an unterminated shell quote is fail-safe (ok=false), never mis-tokenizes and never raises":
    let ccCmd = "gcc -c -w '-I/opt/unterminated -o /cache/mod.c.o /cache/mod.c"
    let inv = deriveDepInvocation(ccCmd)
    check not inv.ok

  test "parses a Make-style dependency list (with backslash continuations) into the header set":
    let ccMOutput = "@pfoo.nim.c.o: /cache/@pfoo.nim.c \\\n" &
                    " /inc/foo.h \\\n" &
                    " /usr/include/stdio.h\n"
    let headers = depIncludeHeaders(ccfGnuMake, ccMOutput,
                                    "/cache/@pfoo.nim.c").headers.mapIt(string(it))
    check headers.len == 2
    check "/inc/foo.h" in headers
    check "/usr/include/stdio.h" in headers
    check "/cache/@pfoo.nim.c" notin headers   # source itself excluded

  test "ccIncludeClosure via an injected synthetic run seam returns headers + a content hash":
    let ccCmd = "gcc -c -I/inc -o out.o /src/mod.c"
    let ccMOutput = "out.o: /src/mod.c /inc/foo.h\n"
    let run: RunProc = proc(cmd: string, args: openArray[string]): tuple[output: string, ok: bool] =
      check cmd == "gcc"
      (output: ccMOutput, ok: true)
    let reader = syntheticReader({"/inc/foo.h": "int x;"}.toTable)
    let res = ccIncludeClosure(ccCmd, run, reader, TrackedRoots())
    check res.ok
    check res.headers == @["/inc/foo.h"]
    check res.contentHash.len > 0

  test "a header's CONTENT change (backport, no path/version change) changes the closure hash":
    let ccCmd = "gcc -c -I/inc -o out.o /src/mod.c"
    let ccMOutput = "out.o: /src/mod.c /inc/foo.h\n"
    let run: RunProc = proc(cmd: string, args: openArray[string]): tuple[output: string, ok: bool] =
      (output: ccMOutput, ok: true)
    let readerOld = syntheticReader({"/inc/foo.h": "struct S { int a; };"}.toTable)
    let readerNew = syntheticReader({"/inc/foo.h": "struct S { int a; int b; };"}.toTable)
    let resOld = ccIncludeClosure(ccCmd, run, readerOld, TrackedRoots())
    let resNew = ccIncludeClosure(ccCmd, run, readerNew, TrackedRoots())
    check resOld.contentHash != resNew.contentHash

  test "a failed cc -M invocation surfaces ok=false, never raises":
    let ccCmd = "gcc -c -I/inc -o out.o /src/mod.c"
    let run: RunProc = proc(cmd: string, args: openArray[string]): tuple[output: string, ok: bool] =
      (output: "", ok: false)
    let res = ccIncludeClosure(ccCmd, run, realFileReader, TrackedRoots())
    check not res.ok
    check res.headers.len == 0

  test "R1b/R4: an undeivable cc -M invocation (too short / unterminated quote) surfaces ok=false, never raises, and never even calls run":
    var runCalled = false
    let run: RunProc = proc(cmd: string, args: openArray[string]): tuple[output: string, ok: bool] =
      runCalled = true
      (output: "should never be reached", ok: true)
    let res = ccIncludeClosure("gcc", run, realFileReader, TrackedRoots())   # too short — no source file
    check not res.ok
    check res.headers.len == 0
    check res.contentHash == ""
    check not runCalled

  test "includeClosureContentHash is order-independent (same set, different input order)":
    let reader = syntheticReader({"/a.h": "AAA", "/b.h": "BBB"}.toTable)
    check includeClosureContentHash(@["/a.h", "/b.h"], reader) ==
          includeClosureContentHash(@["/b.h", "/a.h"], reader)

# ===========================================================================
# Behavior 4 — artifactKeyHash(): normalized-.c ⊕ closure hash
# ===========================================================================

suite "artifactKeyHash — normalized .c content XOR'd (chained) with the closure hash":

  test "identical inputs produce identical keys":
    check artifactKeyHash("same content", "same-closure-hash") ==
          artifactKeyHash("same content", "same-closure-hash")

  test "a tailored .c body (post-normalize) changes the key even with the same closure hash":
    check artifactKeyHash("body A", "closure-x") != artifactKeyHash("body B", "closure-x")

  test "a changed closure hash changes the key even with the same .c body":
    check artifactKeyHash("same body", "closure-x") != artifactKeyHash("same body", "closure-y")

  test "the two components are not simply concatenated/commutative — swapping them changes the key":
    # (a deliberately weak but real sanity check that both components matter)
    check artifactKeyHash("X", "Y") != artifactKeyHash("Y", "X")

  test "R5: two units identical .c + closure but a DIFFERENT normalized cc command produce DIFFERENT artifactKeyHash":
    ## Stage-R's `stageRKey` folds `normalize(ccCmd)` into its key; Stage-M's
    ## `artifactKeyHash` must fold the SAME so M's key is a true PREFIX of
    ## R's — otherwise M can count two units as "shared" (same .c + closure)
    ## that would genuinely MISS under R (different cc flags), over-counting
    ## the measured r_time gate number.
    let k1 = artifactKeyHash("same body", "same-closure", "gcc -O2 -c -o a.o a.c")
    let k2 = artifactKeyHash("same body", "same-closure", "gcc -O3 -c -o a.o a.c")
    check k1 != k2

  test "R5-15: the deprecated 2-arg companion forwards \"\", so it agrees with an explicit empty cc-command":
    ## What this pins CHANGED in round 5 without the assertion changing, which is
    ## worth stating so the next reader does not misread it. It used to pin a
    ## DEFAULT: `normalizedCcCmd` was the third parameter of one proc and
    ## defaulted to "". R5-15 removed that default -- a parameter that is cache
    ## KEY MATERIAL must not be omittable -- and added a `{.deprecated.}` 2-arity
    ## companion forwarding "" so existing calls keep compiling.
    ##
    ## So the equality below now pins the COMPANION'S FORWARDING CONTRACT: the
    ## 2-arg spelling must fold an empty cc-command component and nothing else.
    ## Existing 2-arg call sites (e.g. the committed golden-fixture oracle) depend
    ## on that, and it is the reason removing the default cost zero churn. The
    ## 3-arity proc has no default to test.
    check artifactKeyHash("body", "closure") == artifactKeyHash("body", "closure", "")

# ===========================================================================
# Behavior 5 — reuseRatios(): closed-form r_time/r_size incl. segmentation
# ===========================================================================

suite "reuseRatios — closed-form r_time (primary) / r_size (secondary), segmented":

  test "two entrypoints sharing one unit and diverging on another: r_time and r_size computed correctly":
    let records = @[
      ArtifactRecord(entrypointIdentity: "ep_a", groupId: "g", configHash: "c",
                     basename: "shared.c", keyHash: "K_SHARED", sizeBytes: 100, ccTimeUs: 50),
      ArtifactRecord(entrypointIdentity: "ep_b", groupId: "g", configHash: "c",
                     basename: "shared.c", keyHash: "K_SHARED", sizeBytes: 100, ccTimeUs: 50),
      ArtifactRecord(entrypointIdentity: "ep_a", groupId: "g", configHash: "c",
                     basename: "tailored.c", keyHash: "K_TAILORED_A", sizeBytes: 20, ccTimeUs: 200),
      ArtifactRecord(entrypointIdentity: "ep_b", groupId: "g", configHash: "c",
                     basename: "tailored.c", keyHash: "K_TAILORED_B", sizeBytes: 20, ccTimeUs: 200),
    ]
    let ratios = reuseRatios(records)
    check ratios.len == 1
    let r = ratios[(groupId: "g", configHash: "c")]
    # bytes: shared=200 (100*2), total=240 (200+40) -> r_size = 200/240
    check abs(r.rSize - (200.0 / 240.0)) < 1e-9
    # cc time: shared=100 (50*2), total=500 (100+400) -> r_time = 100/500 = 0.2
    check abs(r.rTime - 0.2) < 1e-9
    check r.rTime != r.rSize   # the exact divergence RFC-0006 names

  test "a keyHash carried by only ONE entrypoint (no cross-entrypoint sharing) contributes nothing to the shared numerator":
    let records = @[
      ArtifactRecord(entrypointIdentity: "ep_a", groupId: "g", configHash: "c",
                     basename: "solo.c", keyHash: "K_SOLO", sizeBytes: 10, ccTimeUs: 10),
    ]
    let r = reuseRatios(records)[(groupId: "g", configHash: "c")]
    check r.rTime == 0.0
    check r.rSize == 0.0

  test "the same entrypoint appearing twice under the same keyHash does NOT count as cross-entrypoint sharing":
    let records = @[
      ArtifactRecord(entrypointIdentity: "ep_a", groupId: "g", configHash: "c",
                     basename: "x.c", keyHash: "K", sizeBytes: 10, ccTimeUs: 10),
      ArtifactRecord(entrypointIdentity: "ep_a", groupId: "g", configHash: "c",
                     basename: "x.c", keyHash: "K", sizeBytes: 10, ccTimeUs: 10),
    ]
    let r = reuseRatios(records)[(groupId: "g", configHash: "c")]
    check r.rTime == 0.0
    check r.rSize == 0.0

  test "segmentation: two different (groupId, configHash) segments are computed independently":
    let records = @[
      # segment (g1, c1): fully shared
      ArtifactRecord(entrypointIdentity: "ep_a", groupId: "g1", configHash: "c1",
                     basename: "u.c", keyHash: "K1", sizeBytes: 100, ccTimeUs: 100),
      ArtifactRecord(entrypointIdentity: "ep_b", groupId: "g1", configHash: "c1",
                     basename: "u.c", keyHash: "K1", sizeBytes: 100, ccTimeUs: 100),
      # segment (g2, c2): fully unshared (distinct keyHash per entrypoint)
      ArtifactRecord(entrypointIdentity: "ep_a", groupId: "g2", configHash: "c2",
                     basename: "u.c", keyHash: "K2A", sizeBytes: 100, ccTimeUs: 100),
      ArtifactRecord(entrypointIdentity: "ep_b", groupId: "g2", configHash: "c2",
                     basename: "u.c", keyHash: "K2B", sizeBytes: 100, ccTimeUs: 100),
    ]
    let ratios = reuseRatios(records)
    check ratios.len == 2
    check ratios[(groupId: "g1", configHash: "c1")].rTime == 1.0
    check ratios[(groupId: "g2", configHash: "c2")].rTime == 0.0

  test "an empty record set yields an empty segment table":
    check reuseRatios(@[]).len == 0

# ===========================================================================
# Behavior 6 — CR3: ccIncludeClosure must resolve a reported header's CASE
# before it becomes identity/key material (the W1 gate, `paths.classify`'s
# `ReportedPath` overload — CR10, applied to artifactid's SECOND consumer of
# a dependency report).
# ===========================================================================

suite "ccIncludeClosure — CR3: a mis-cased reported header must not desync the closure hash":
  ## Models the MSVC shape: `/sourceDependencies-` lowercases every path it
  ## reports, unconditionally, while a gcc/clang `-M` report echoes the
  ## `#include` directive's own literal (here: real-case) spelling. Both
  ## reports name the SAME on-disk file. Pre-fix, `includeClosureContentHash`
  ## chains the raw reported path string into the hash BEFORE the header's
  ## content (`includeClosureContentHash`'s `fnv1a64(... & p & "\x00" & c)`
  ## fold), so the two reports hash differently even
  ## though the file is byte-identical — a permanent cross-toolchain
  ## `keyHash` desync that skews the `--measure-compile-reuse` r_time/r_size
  ## telemetry (CR3). Post-fix, both resolve to the SAME real on-disk
  ## spelling via `classify`'s `ReportedPath` overload before hashing, so
  ## the two hashes agree.

  proc fixedProbe(policy: FoldPolicy): proc (rootAbs, stateDir: string): Option[FoldPolicy] =
    result = proc (rootAbs, stateDir: string): Option[FoldPolicy] = some(policy)

  proc rootsWith(projectAbs: string; policy: FoldPolicy): TrackedRoots =
    initTrackedRoots(projectAbs, @[], "", fixedProbe(policy))

  const realCaseHeader  = "/fake/proj-cr3/Native/Add.h"
  const lowerCaseHeader = "/fake/proj-cr3/native/add.h"
  const sourceFile      = "/fake/proj-cr3/src/mod.c"
  const ccCmd = "gcc -c -I/fake/proj-cr3/src -o out.o " & sourceFile

  proc fakeExpand(p: string): string =
    ## Models the real on-disk-spelling resolver (`GetFinalPathNameByHandleW`
    ## on a real Windows/case-insensitive volume): whatever case it is
    ## handed, it answers with the ONE true on-disk spelling — exactly the
    ## `paths.CandidateExpander` seam `classify` already exercises this way
    ## in tests/unit/test_paths.nim's own W1 vectors.
    if p.toLowerAscii == lowerCaseHeader: realCaseHeader else: p

  proc makeRun(reportedHeader: string): RunProc =
    let ccMOutput = "out.o: " & sourceFile & " " & reportedHeader & "\n"
    result = proc(cmd: string, args: openArray[string]): tuple[output: string, ok: bool] =
      (output: ccMOutput, ok: true)

  proc caseInsensitiveReader(path: string): tuple[content: string; ok: bool] =
    ## A real case-insensitive disk read: BOTH spellings of the same file
    ## answer with IDENTICAL content, exactly as a real folding filesystem
    ## would — isolating the bug to the PATH STRING folded into the hash,
    ## never the content.
    if path.toLowerAscii == lowerCaseHeader:
      (content: "struct S { int a; };", ok: true)
    else:
      (content: "", ok: false)

  test "RED (documents the pre-fix defect): with an explicitly EMPTY TrackedRoots, a real-case report and a lowercased report of the SAME file still hash differently":
    ## CR10: `roots` no longer DEFAULTS to the unpopulated zero value — every
    ## call site must now name it. This test pins the documented residual of
    ## an EXPLICITLY-empty `TrackedRoots()` (never resolves case — see this
    ## module's doc for why), so it doesn't silently regress into "always
    ## fixed" without anyone noticing the behavior changed.
    let resGcc  = ccIncludeClosure(ccCmd, makeRun(realCaseHeader), caseInsensitiveReader,
                                   TrackedRoots())
    let resMsvc = ccIncludeClosure(ccCmd, makeRun(lowerCaseHeader), caseInsensitiveReader,
                                   TrackedRoots())
    check resGcc.ok
    check resMsvc.ok
    check resGcc.contentHash != resMsvc.contentHash   # same file, different hash: the bug

  test "FIXED: with TrackedRoots supplied, the two reports resolve to the SAME real spelling and hash identically":
    let roots = rootsWith("/fake/proj-cr3", fpAsciiLower)
    let resGcc  = ccIncludeClosure(ccCmd, makeRun(realCaseHeader), caseInsensitiveReader,
                                   roots, fakeExpand)
    let resMsvc = ccIncludeClosure(ccCmd, makeRun(lowerCaseHeader), caseInsensitiveReader,
                                   roots, fakeExpand)
    check resGcc.ok
    check resMsvc.ok
    check resGcc.headers == resMsvc.headers           # resolved to the same real spelling
    check resGcc.contentHash == resMsvc.contentHash   # CR3: same file -> same hash

    # ...and the downstream artifactKeyHash the reuse-ratio telemetry
    # actually keys on agrees too.
    let keyGcc  = artifactKeyHash("same .c body", resGcc.contentHash)
    let keyMsvc = artifactKeyHash("same .c body", resMsvc.contentHash)
    check keyGcc == keyMsvc

  test "a genuinely-outside (system) header is kept, not silently dropped, when roots are supplied":
    ## UNLIKE closure.extractCompileInputs' tracked-closure loop (which drops
    ## anything outside every root), ccIncludeClosure must keep system
    ## headers: RFC-0006's soundness argument is that a libc/header upgrade
    ## must remain visible in the hash (module doc's cc -M, not -MM,
    ## rationale). This is the documented reason the two loops are NOT
    ## unified behind one drop-outside-roots helper.
    let roots = rootsWith("/fake/proj-cr3", fpAsciiLower)
    let ccMOutput = "out.o: " & sourceFile & " /usr/include/stdint.h\n"
    let run: RunProc = proc(cmd: string, args: openArray[string]): tuple[output: string, ok: bool] =
      (output: ccMOutput, ok: true)
    let reader = proc(path: string): tuple[content: string; ok: bool] =
      (content: "typedef long intptr_t;", ok: true)
    let res = ccIncludeClosure(ccCmd, run, reader, roots, fakeExpand)
    check res.ok
    check res.headers == @["/usr/include/stdint.h"]

# ===========================================================================
# Behavior 7 — round-2 review (MEDIUM): a /sourceDependencies document whose
# own Data.Source names a DIFFERENT translation unit than the one just
# probed (W9j's `dscMismatch`) must fail as loudly as a `DepProbeError` --
# never fall through as an empty-but-successful closure. Pre-fix,
# `ccIncludeClosure` checked only `probed.err != dpeNone` and never read
# `probed.sourceCheck`, so this exact case returned `ok: true,
# probeErr: cpeNone` with an empty header set indistinguishable from a
# genuine empty closure. Mirrors closure.extractCompileInputs's raise on the
# identical signal.
# ===========================================================================

suite "ccIncludeClosure — round-2 review: a Data.Source mismatch must fail loudly, not as an empty successful closure":

  test "a stale/misattributed /sourceDependencies document surfaces ok=false, probeErr=cpeSourceMismatch, and a message naming the mismatch":
    ## `cl` is on `MsvcDrivers`, so `deriveDepInvocation` classifies this
    ## `ccCmd` as `ccfMsvc` and `depIncludeHeaders` parses the run's output
    ## with the `/sourceDependencies` JSON parser. The document below is
    ## well-formed and its Includes are real, but `Data.Source` names
    ## "OTHER.c" -- a different translation unit than `add.c`, the one this
    ## probe was actually for (mirrors test_ccprobe.nim's own dscMismatch
    ## fixture).
    let ccCmd = "cl /c /Foout.obj c:/p/native/add.c"
    let staleDoc = "unit.c\n" & """{
    "Version": "1.2",
    "Data": {
        "Source": "c:\\p\\native\\OTHER.c",
        "Includes": [ "c:\\p\\native\\add.h" ]
    }
}
"""
    let run: RunProc = proc(cmd: string, args: openArray[string]): tuple[output: string, ok: bool] =
      (output: staleDoc, ok: true)
    let res = ccIncludeClosure(ccCmd, run, realFileReader, TrackedRoots())
    check not res.ok
    check res.probeErr == cpeSourceMismatch
    check res.headers.len == 0
    check res.contentHash == ""
    check "DIFFERENT translation unit" in res.errMsg
    check "/sourceDependencies" in res.errMsg   # names the ACTUAL probe family, not a hard-coded GNU spelling

when isMainModule:
  echo "All artifactid tests passed."
